### PR TITLE
Fix #1435

### LINKED ISSUE #1435: Indent() not working for anonymous functions
@thofma 
```
julia> import AbstractAlgebra.PrettyPrinting.pretty

julia> import AbstractAlgebra.PrettyPrinting.Indent

julia> f = x-> 2*x
#15 (generic function with 1 method)

julia> print(pretty(stdout),Indent(),f)
#15
julia> print(pretty(stdout),Indent(),"test")
  test
```

### PR DESCRIPTION
**Pull request by thofma**
- Fix #1435
- Bump version

### CODE REVIEW

File: src/PrettyPrinting.jl [hunk 1]
```diff
@@ -1546,6 +1546,8 @@ write_indent(io::IO) = write(_unwrap(io).io, io.indent_str^io.indent_level)
 
 write(io::IOCustom, chr::Char) = write(io, string(chr)) # Need to catch writing a '\n'
 
+write(io::IOCustom, chr::Symbol) = write(io, string(chr)) # Need to catch writing a '\n'
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1549]: This adds one invalidation. We can live with that for now. But I wonder if we shouldn't instead replace this and the one for char, and also `write(io::IOCustom, str::String)` by a single method for `unsafe_write(io::IOCustom, ref, nbytes::UInt)` which they all end up calling?

Comment (fingolfin) [reply src/PrettyPrinting.jl:1549]: Note that even if the data then is a byte stream, we don't have to worry about things like decoding UTF-8 or so -- the byte for `\n` is never part of a multibyte UTF-8 character.

Comment (fingolfin) [reply src/PrettyPrinting.jl:1549]: It would also allow removing
```
# Base.write on an IOContext does not call Base.write on the unwrapped context ...
Base.write(io::IOContext{<: IOCustom}, s::Union{SubString{String}, String}) = Base.write(Base.unwrapcontext(io)[1], s)
```
and maybe more, like 
```
Base.write(io::IOContext{<: IOCustom}, s::Char) = Base.write(Base.unwrapcontext(io)[1], s)
```

Conversely, if we don't provide `unsafe_write`, then perhaps this PR also needs `Base.write(io::IOContext{<: IOCustom}, s::Symbol) = Base.write(Base.unwrapcontext(io)[1], s)` ????


Anyway, now that I look at the code closer, I guess in order to implement `_write_line` right we need at least some UTF-8 handling after all... but I guess in the worste case, we could just convert the `Ptr{UInt8}` back into a `String` ;-)

**Comment by fingolfin** [comment]
With the 5GB limit 1.10 passes just fine, but nightly is stuck with a full heap, collecting tiny amounts of memory in never ending collections:
```
...
Heap stats: bytes_mapped 3840.94 MB, bytes_resident 1555.33 MB,
heap_size 5129.76 MB, heap_target 5120.00 MB, Fragmentation 348.055
GC: pause 449.67ms. collected 0.551529MB. full 
Heap stats: bytes_mapped 3840.94 MB, bytes_resident 1555.33 MB,
heap_size 5123.29 MB, heap_target 5120.00 MB, Fragmentation 349.884
GC: pause 486.68ms. collected 0.322746MB. full 
Heap stats: bytes_mapped 3840.94 MB, bytes_resident 1555.33 MB,
heap_size 5120.00 MB, heap_target 5120.00 MB, Fragmentation 351.261
GC: pause 485.41ms. collected 0.235336MB. full 
Heap stats: bytes_mapped 3840.94 MB, bytes_resident 1555.33 MB,
heap_size 5125.18 MB, heap_target 5120.00 MB, Fragmentation 352.193
GC: pause 460.01ms. collected 0.345070MB. full 
Heap stats: bytes_mapped 3840.94 MB, bytes_resident 1555.33 MB,
heap_size 5120.42 MB, heap_target 5120.00 MB, Fragmentation 353.894
GC: pause 467.79ms. collected 0.347397MB. full 
Heap stats: bytes_mapped 3840.94 MB, bytes_resident 1555.33 MB,
heap_size 5122.13 MB, heap_target 5120.00 MB, Fragmentation 355.076
GC: pause 445.63ms. collected 0.510376MB. full 
...
```

That suggests memory usage has grown considerably from Julia 1.10 to nightly/master. Would be good to find out what; perhaps we should file a separate Julialang issue for that?

**Comment by thofma** [comment]
Comment for wrong PR?

**Comment by fingolfin** [comment]
Indeed
