### PR TITLE
Fix powering of multivariates over a ring of char != 0

### LINKED ISSUE #543: Powering fails for multivariates over a finite field
The pow_fps algorithm doesn't handle characteristic not equal to zero. Occasionally it fails with a division by zero error, but most of the time it just hangs or returns incorrect results:

```
R, (x, y, z, t) = PolynomialRing(GF(2), ["x", "y", "z", "t"])
f = (1+x+y+z+t)^3
f = (1+x+y+z+t)^4
```

### PR DESCRIPTION
**Pull request by wbhart**
This adds a characteristic function where it was missing, so that multivariates do the right thing.

Note that characteristic need not be defined for any given ring, but if it is and the char = 0, we get faster powering of multivariates over that ring.

I have written the code for Nemo also (not that it is required for correctness), and will make a PR as soon as I write the test code for it.

Closes #543

### CODE REVIEW

**Comment by wbhart** [comment]
Note that pow_rmul will be woefully inefficient, but at least it is correct.

File: src/generic/AbsSeries.jl [hunk 1]
```diff
@@ -134,6 +134,10 @@ function Base.hash(a::AbstractAlgebra.AbsSeriesElem, h::UInt)
    return b
 end
 
+function characteristic(a::AbsSeriesRing{T}) where T <: RingElement
```
Comment (rfourquet) [inline src/generic/AbsSeries.jl]: The `where T <: RingElement` can be removed, it just adds noise. The `where T` construct should in general be used only for dispatch purposes, to restrict the accepted types, which is not the case here (and then, the convention is to write e.g.  `characteristic(a::AbsSeriesRing{<:SomeRings})` if `T` is not used within the function body.)

File: src/generic/LaurentSeries.jl [hunk 2]
```diff
@@ -400,6 +400,10 @@ function renormalize!(z::LaurentSeriesElem)
    return nothing
 end
 
+function characteristic(a::LaurentSeriesRing{T}) where T <: RingElement
+   return characteristic(base_ring(a))
+end
```
Comment (rfourquet) [inline src/generic/LaurentSeries.jl]: Similar suggestion (it's lighter on the eyes): `characteristic(a::LaurentSeriesRing) = characteristic(base_ring(a))`

File: src/generic/MPoly.jl [hunk 3]
```diff
@@ -2409,11 +2427,15 @@ function ^(a::MPoly{T}, b::Int) where {T <: RingElement}
...
       return parent(a)([coeff(a, 1)^b], exps)
    elseif b == 0
-      return parent(a)(1)
+      return one(parent(a))
    elseif b == 1
-      return a
+      return deepcopy(a)
    elseif b == 2
       return a*a
+   elseif !hasmethod(characteristic, Tuple{T}) ||
```
Comment (rfourquet) [inline src/generic/MPoly.jl]: Just an idea: what about defining a fallback `charasteristic(x) = missing` ? Then the `hasmethod` call can be avoided (it's not very efficient, even though in this case it probably doesn't matter).

File: src/generic/MPoly.jl [hunk 4]
```diff
@@ -2393,6 +2397,20 @@ function pow_fps(f::MPoly{T}, k::Int, bits::Int) where {T <: RingElement}
    return parent(f)(Rc, Re)
 end
 
+function pow_rmul(a::MPoly{T}, b::Int) where {T <: RingElement}
+   b < 0 && throw(DomainError(b, "exponent must be >= 0"))
+   if length(a) == 0
+      return parent(a)()
```
Comment (rfourquet) [inline src/generic/MPoly.jl]:
```suggestion
      return zero(a)
```

File: src/generic/MPoly.jl [hunk 5]
```diff
@@ -2393,6 +2397,20 @@ function pow_fps(f::MPoly{T}, k::Int, bits::Int) where {T <: RingElement}
    return parent(f)(Rc, Re)
 end
 
+function pow_rmul(a::MPoly{T}, b::Int) where {T <: RingElement}
+   b < 0 && throw(DomainError(b, "exponent must be >= 0"))
+   if length(a) == 0
```
Comment (rfourquet) [inline src/generic/MPoly.jl]: Can it be changed to `iszero(a)` ?

File: src/generic/MPoly.jl [hunk 6]
```diff
@@ -2393,6 +2397,20 @@ function pow_fps(f::MPoly{T}, k::Int, bits::Int) where {T <: RingElement}
...
+      return parent(a)()
+   elseif b == 0
+      return one(parent(a))
```
Comment (rfourquet) [inline src/generic/MPoly.jl]:
```suggestion
      return one(a)
```

File: src/generic/AbsSeries.jl (hunk 1 above)
Comment (thofma) [reply src/generic/AbsSeries.jl]: It also serves as implicit documentation though.

Comment (wbhart) [reply src/generic/AbsSeries.jl]: The type shouldn't be Any here. 

Are you absolutely sure the variant you give is equivalent? I thought that was now used for specifying covariance, whereas "where" is for a unionall or some such thing.

I've been using "where" as it seems to be correct for the cases we use it.

I'm not sure if the two different notations would make any real difference here. But I think that conceptually they are different.

File: src/generic/LaurentSeries.jl (hunk 2 above)
Comment (wbhart) [reply src/generic/LaurentSeries.jl]: It overflows the 80 character line.

File: src/generic/MPoly.jl (hunk 3 above)
Comment (wbhart) [reply src/generic/MPoly.jl]: Yes, I will do this.

File: src/generic/AbsSeries.jl (hunk 1 above)
Comment (rfourquet) [reply src/generic/AbsSeries.jl]: You can see it like that, but `where` was never meant for documentation. In this function, I don't need to receive the information that `AbsSeriesRing` is defined only for `RingElement`. A `where` clause in a function catches the attention of the reader, it signifies: I will only work for these specific `T`s, it's a filter for dispatch. To add a filter which filters nothing out is a useless load on the reader. In addition, it requires more maintenance, as now it must be updated if `AbsSeries` is modified to accept more types.

File: src/generic/MPoly.jl (hunk 5 above)
Comment (wbhart) [reply src/generic/MPoly.jl]: I suppose so

File: src/generic/AbsSeries.jl (hunk 1 above)
Comment (rfourquet) [reply src/generic/AbsSeries.jl]: > Are you absolutely sure the variant you give is equivalent?

In this case yes, as `AbsSeriesRing{T}` is defined only for `T <: RingElement`. I don't really understand your comment about covariance.

> But I think that conceptually they are different.

They are somewhat conceptually different, as I said in my previous comment: a `where` in a function is for dispatch only, so by putting it here you send the message that a dispatch thing is happening with the type parameter, when actually there is none. That said, if you envision the possibility to widen the accepted type parameters for `AbsSeriesRing`, for which this definition of `characteristic` would be wrong, then it could make sense to keep the type constraint on `T` in this method signature. Otherwise, no.

Comment (rfourquet) [reply src/generic/AbsSeries.jl]: If you are interested, there is a couple of corner cases where adding a `where` clause is different, as it forces specialization (so it's still semantically equivalent): cf. https://docs.julialang.org/en/v1.4-dev/manual/performance-tips/#Be-aware-of-when-Julia-avoids-specializing-1

Comment (thofma) [reply src/generic/AbsSeries.jl]: I don't mean where or not. I meant being more explicit about the types in the signatures.

And yes we also want specialization on all types.

File: src/generic/LaurentSeries.jl (hunk 2 above)
Comment (rfourquet) [reply src/generic/LaurentSeries.jl]: I though the limit was 92, but my suggestion here takes 68 characters.

File: src/generic/AbsSeries.jl (hunk 1 above)
Comment (wbhart) [reply src/generic/AbsSeries.jl]: There are things like group rings and so on where you have group elements instead of ring elements. I'd prefer to keep the restriction, as this code is only valid when there is a ring. Besides that, we have done this throughout much of AbstractAlgebra and Nemo, and it would be major diversion to fix it everywhere.

Also, we do use it for documentation purposes. We try to keep the docstrings and the function prototypes the same. This way the reader of the documentation sees the restriction explicitly.

Maybe one day we decide to change our minds on this. But for now, that's how it's been done.

File: src/generic/MPoly.jl (hunk 4 above)
Comment (wbhart) [reply src/generic/MPoly.jl]: Fixed.

File: src/generic/MPoly.jl (hunk 5 above)
Comment (wbhart) [reply src/generic/MPoly.jl]: Fixed.

File: src/generic/MPoly.jl (hunk 6 above)
Comment (wbhart) [reply src/generic/MPoly.jl]: Fixed.

File: src/generic/AbsSeries.jl (hunk 1 above)
Comment (rfourquet) [reply src/generic/AbsSeries.jl]: > And yes we also want specialization on all types.

Sure, but my remark on specialization doesn't apply in this case, I mention it just FYI.

> I don't mean where or not. I meant being more explicit about the types in the signatures.

The topic was `where` clauses, so I'm not sure what you mean. But I would like to know what is the purpose of repeating the type constraints in all methods applying to this type when the type constraint is already on the type itself. It's a Julia anti-pattern.

Comment (rfourquet) [reply src/generic/AbsSeries.jl]: > We try to keep the docstrings and the function prototypes the same

It should be also removed from the docstrings, it's a useless load on the user, and hurts the eye of some julia developers.
It doesn't have to be fixed all at once.

Comment (wbhart) [reply src/generic/AbsSeries.jl]: Because if we ever lift that restriction on the type, we'd need to go through and add precisely all the restrictions that are now there to be sure that it still works the way that was intended by the people who wrote the functions.

I recall Jeff Bezanson complaining about us doing this, very early on in the development of Nemo. We simply disagreed and have quite often written the restriction on the functions.

I agree that it is more typing and it makes it look more cluttered. But for mathematics, it isn't an awful choice.

Anyhow, I'm not going to go through and change the million or so such cases right now, and that would be orthogonal to this PR. So let's leave it for now. Maybe one day we change our minds. But it's certainly been a deliberate choice on our part.

File: src/generic/LaurentSeries.jl (hunk 2 above)
Comment (wbhart) [reply src/generic/LaurentSeries.jl]: Only if you remove the "where", which I see no overwhelming reason to do. It is a distraction.

File: src/generic/MPoly.jl (hunk 3 above)
Comment (wbhart) [reply src/generic/MPoly.jl]: Done.

File: src/generic/AbsSeries.jl (hunk 1 above)
Comment (wbhart) [reply src/generic/AbsSeries.jl]: The difference is we are writing a maths library, not a library of container types.

Comment (rfourquet) [reply src/generic/AbsSeries.jl]: > Because if we ever lift that restriction on the type, we'd need to go through and add precisely all the restrictions that are now there to be sure that it still works the way that was intended by the people who wrote the functions.

It's not a clear win: without these constraints on the methods, you might want to go through all the methods to be sure that they are still valid, and you might have to add constraints on a few of them. With the current setting, you would probably have to update most of them, as they work equally well with the new possible type parameters. 

> I'm not going to go through and change the million or so such cases right now,

I certainly didn't request that. I would hope that the bar to make a cosmetic change like that isn't to change everything all at once. It's then very discouraging.

Otherwise sure, it's orthogonal to this PR.

> But it's certainly been a deliberate choice on our part.

Ok, it sounded otherwise in your previous comment, where you had concerns about covariance and stuff.

File: src/generic/LaurentSeries.jl (hunk 2 above)
Comment (rfourquet) [reply src/generic/LaurentSeries.jl]: > It is a distraction.

Seriously, I will sutt up after this one, but the `where` **is** the distraction.

File: src/generic/AbsSeries.jl (hunk 1 above)
Comment (wbhart) [reply src/generic/AbsSeries.jl]: Of course that has to be the bar. If you change it in some places and not others, people will use examples where it hasn't been changed as an excuse to not change their own code.

And making that the bar prevents people from wasting enormous quantities of time on things that have already been decided long ago because they personally think it should look different.

As I've said before, when I work on a project, I always try to adopt precisely the same conventions as the people who maintain the project, even if they are not the conventions I like. I don't try to change the conventions because I personally think they should have picked a different convention.

Of course, suggesting that there is an improvement to be made is fine. But I think you agree, changing this everywhere would be a massive waste of time, especially given the time constraints we have.

The priority has to be given to fixing things that close actual open tickets, not making cosmetic changes to conventions because of personal preferences!

File: src/generic/LaurentSeries.jl (hunk 2 above)
Comment (wbhart) [reply src/generic/LaurentSeries.jl]: I was going home at 5pm. It's nearly 6pm now. It's wasted heaps of my time arguing about something that will have absolutely zero impact on any open tickets! We have a computer algebra system to write. We can't spend all our time amending code according to conventions that are the opposite to the ones we already use!

File: src/generic/RelSeries.jl [hunk 7]
```diff
@@ -234,6 +234,10 @@ function renormalize!(z::AbstractAlgebra.RelSeriesElem)
    return nothing
 end
 
+function characteristic(a::RelSeriesRing{T}) where T <: RingElement
+   return characteristic(base_ring(a))
+end
```
Comment (rfourquet) [inline src/generic/RelSeries.jl]: Instead of having to define it for all series types unders the sun, it could be nice to define a generic `characteristic(a::AbstractAlgebra.SeriesRing) = characteristic(base_ring(a))` and be done for the definition for most (all?) of them. Migth apply to other abstract types as well.

Comment (rfourquet) [reply src/generic/RelSeries.jl]: E.g `PolyRing`.

Comment (wbhart) [reply src/generic/RelSeries.jl]: I don't know if that would be correct. So I haven't done this.

It's not so obvious that it would be correct for all possible implementations. For example, the characteristic of GF(p) is p, but if you think of p-adics as being a power series with elements in GF(p) (with carries), which some package might actually do, this would be incorrect.

Probably I am worrying unnecessarily here. But I did not define it for all series types on purpose. I cannot imagine what we will consider to be a series type in future, let alone what others will. And characteristic is pretty important to get right.

File: src/generic/AbsSeries.jl (hunk 1 above)
Comment (rfourquet) [reply src/generic/AbsSeries.jl]: I have made clear that I didn't suggest to change everything, and I initiated the discussion because the reason for the `where` was not clear to me, I though it was an oversight. You don't need to waste more time telling me that we must not spend huge amount of time on trivialities, I have already completely understood this and this is not my intention. Nor that I should be more respectful of the conventions of a project. I generally try to follow them and to be a "good Open Source contributor" (to use your terms). But I can't stay silent if I believe something is a mistake.

Comment (rfourquet) [reply src/generic/AbsSeries.jl]: > Of course that has to be the bar.

The problem with this approach is that then: just assuming for one moment that you agree with the proposed change here for the sake of the argument, then the change could be made only eventually, when we can afford to spend some time on it. But for consistency, we keep the current way for new code, which means that we increase the work which has to be done eventually. So of course, consistency is nice, but for cosmetic changes like that it has a price that I think is too high to pay.

Comment (wbhart) [reply src/generic/AbsSeries.jl]: We can hire a HiWi to do stuff like this. It's a complete waste of developer effort. That's assuming we agreed to the change, which I don't at present. And unless I misunderstand, nor does @thofma

We seriously need to focus on the stuff we know is broken and for which there is a clear benefit to fix. There is so much of it we are literally drowning in it at present.

Your argument about keeping the current way only increasing work later is absolutely valid, *if* we had made a decision to make the change, which we have not. But once we make that decision, we would put someone on the task and get it all done. Simply starting and not finishing hundreds of changes which we'd eventually like to have will leave the entire library in an unmaintainable mess. We must value consistency where it is possible.

Comment (wbhart) [reply src/generic/AbsSeries.jl]: Anyway, let's not talk hypotheticals. On the way home I tried to think through what might happen in the future. I thought of four different possibilities:

1) Extension of the current RingElement type to something more general. We already have non-commutative rings, for which polynomials for example, have their own special type NCPoly (IIRC). But it is certainly feasible that we decide to have polynomials or series or some other thing that currently depends on coefficients being in a commutative ring that we want to lift that restriction for.

2) There are multiple packages out there that depend on our type hierarchy. Perhaps one of the packages needs to define polynomials over their special types which do not satisfy our RingElement interface, and the easiest way to do it is to extend the type to a union of our RingElement and their type (or some abstract type they create in AbstractAlgebra for this purpose). Then they go through and modify the handful of functions that won't work with their funky type.

3) Inexact rings can get really problematic. We might eventually decide to push them outside RingElement for some reason.

4) In implementing some bizarre mathematical structure, we decide the easiest way is to allow polynomials or series or some other type to accept something other than RingElement's for coefficients, and to build the new type around such extended polynomials, ensuring that the various functions required for that are extended to accept that new type.

Those are the three potential cases I can think of. I can't see any clearer than anyone else how likely any of these are, or how much of a burden it would be in either direction to do this sort of thing. But the fact remains that in mathematics, specifying exactly which kinds of objects are acceptable is fairly important. Simply accepting Any really jars my mathematical intuition, even if the type itself is currently so restricted.

Comment (wbhart) [reply src/generic/AbsSeries.jl]: Having said all that, I do agree that the current convention Julia uses is correct for Julia. Many more of their objects are generic containers, and simply restricting things unnecessarily usually just leads to users complaining they can't do something that they otherwise could do if it weren't so restricted. This is a case Jeff Bezanson has made, and I agree with him on it, for the specific case of a general purpose language such as Julia.

**Comment by fieker** [comment]
On Tue, Dec 03, 2019 at 09:13:14AM -0800, wbhart wrote:
> wbhart commented on this pull request.
> 
> 
> 
> > @@ -234,6 +234,10 @@ function renormalize!(z::AbstractAlgebra.RelSeriesElem)
>     return nothing
>  end
>  
> +function characteristic(a::RelSeriesRing{T}) where T <: RingElement
> +   return characteristic(base_ring(a))
> +end
> 
> I don't know if that would be correct. So I haven't done this.
> 
> It's not so obvious that it would be correct for all possible implementations. For example, the characteristic of GF(p) is p, but if you think of p-adics as being a power series with elements in GF(p) (with carries), which some package might actually do, this would be incorrect.

NO: p-adics are char 0, always, everywhere.
Rings of inifinte length Witt-Vectors over a finite field, also known as
Z_q or Z_p are still char 0
If a package wants char p p-adics, they have to do this outside our
hierarchy

File: src/generic/LaurentSeries.jl (hunk 2 above)
Comment (rfourquet) [reply src/generic/LaurentSeries.jl]: I'm sorry you take it like this. I regret my last comment above, which was not constructive. Otherwise, I'm sincerely sorry that you feel you wasted your time, but I won't take any blame for this. It's your responsibility if you engage in a discussion which you consider useless.

My motivation in reviewing a PR is to make this project as successful as possible within my understanding of the constraints. My goal is _not_ to make cosmetic changes just according to my current personal preferences. If a review comment of mine is dismissed and answered with something like "no, we just do it this way", I won't argue, I understand that my decisional power is null, and I'm no more happy than you are to waste my time in pointless argumentations. On the other hand, if my comment is met with arguments to explain why this is the way it is, it's only natural to expect counter-arguments if anyone has to share any.

I find your comment above very negatively dismissive, it suggests that my contributions are not welcomed here, at least unless I'm sure they have sufficient value in the eyes of the maintainers. I learn slowly what that means, but again, I usually contribute what I think is valuable to the project.

> We can't spend all our time amending code according to conventions that are the opposite to the ones we already use!

 In the present case of this PR, I initially didn't get from the comments that it was a convention, it really looked like an oversight. So sure, I agree that "We can't spend all our time amending code according to conventions that are the opposite to the ones we already use", but I didn't suggest such a thing here. And I'm already aware that you don't like suggestions to change these custom conventions, so I usually try to refrain from from that.

**Comment by wbhart** [comment]
@fieker I am not sure which direction you are arguing here. I agree p-adics are char 0 in every case. But what would be the characteristic of the "base ring"?

Anyhow, this is not much of a serious example, since no one is suggesting making p-adics belong to our power series hierarchy (I think).

I'm happy if you want to put in the characteristic(S) = characteristic(base_ring(S)) for polynomials and power series. With so many weird and wonderful things in mathematics, I just wasn't sure this would always be correct in the presence of say inexact rings, etc. Probably. But I wasn't sure, and so deliberately didn't do this.

File: src/generic/RelSeries.jl (hunk 7 above)
Comment (rfourquet) [reply src/generic/RelSeries.jl]: This makes some sense, as `characteristic` is currently not in the mandatory interface for `SeriesRing`. So someone implementing a `SeriesRing` subtype is certain to not have a wrong answer, it will just get a `MethodError` when `characteristic` is needed. The drawback is that it forces this someone to implement `characteristic` if he needs the functionality (e.g. for `^` in this case). So I find the alternative to define generically `characteristic(a::AbstractAlgebra.SeriesRing) = characteristic(base_ring(a))` more pragmatic, in the case we expect it to almost never be wrong:
1. It allows almost everybody to not have to implement it
2. On the other hand, it has to be put in the docs, something along the lines of: "if you implement a subtype of `SeriesRing`, you must implement `characteristic` if your type behaves weirdly".

But the fact that `^` requires `characteristic` to be implemented suggests that it should be put in the docs anyway. So I would favor allowing people to have to do less work, at the risk of getting the wrong answer if someone implements a weird type and doesn't implement the required interface for weird types.

Just my opinion though, I won't argue for it.

File: src/generic/LaurentSeries.jl (hunk 2 above)
Comment (wbhart) [reply src/generic/LaurentSeries.jl]: @rfourquet Your contributions and suggestions are always welcome here. You surely know that by now. In fact, I didn't initially try to just shut down your suggestion precisely because I wanted to hear you out on your reasons. But in my opinion it is quite obvious that in our code we do this all over the place. I am sure the reason is not obvious, and it is done inconsistently.

The history of this is that we initially started doing what you suggested, because we understood that it was making lighter work for the type checker and that there should be some performance benefit. It became clearer over the time (to me) that this was likely not the case (I did a lot of experiments in this direction in the MPoly module). And over time we have drifted much more towards putting this information in for mathematical correctness and documentation.

It could change again in the future as people see a different dimension to the project. But as always, we would need a concensus on the matter from everyone (including you). At the current point in time, I personally don't agree to the change. If I am overruled, and we have the resources to make such a change globally across the package, I will accept the decision. But as I have suggested over and over again, I think that we have much, much more important things to worry about right now. We really have to start focusing our developer effort on things that will maximise the benefit for our users and the grant that pays our salaries. We need to prioritise things on this basis, not on how beautiful things will be if we make this or that change.

Comment (rfourquet) [reply src/generic/LaurentSeries.jl]: > it is quite obvious that in our code we do this all over the place 

Indeed, but it looks like the result of a misunderstanding. I've never seen this style elsewhere and it seems so heavyweigthed and counter-productive to me that I could not imagine it was a deliberate convention. Like all the docstrings prefixed with `@doc Markdown.doc`: I clearly thought it's a result of the belief that it's necessary (it's probably only useful for when there is latex and backslashes, and then I think the documented way is to use a `raw` string, but anyway). So of course I wonder now whether this could be another implicit convention. 

> But as I have suggested over and over again, I think that we have much, much more important things to worry about right now. [...]

Yes, and I wonder why you feel the need to patronize me on this again. I've made clear that I didn't suggest anything here that would cost developer time. I only suggested to amend _this_ PR (not all the repository), because, in my opinion, it saves maintenance effort in the future, and it makes it easier to read the code. So my goal is the opposite of wasting developer time, and this is not about beauty. The idea that I would want us to waste time on useless stuff is imagined. For example, I suggested [above](https://github.com/Nemocas/AbstractAlgebra.jl/pull/544#discussion_r353287412) that "It should be also removed from the docstrings", because I feel it's a documentation issue (and actually I had started preparing a doc PR for something quite related some weeks ago). But I didn't ask anyone to do it, even less to do it all at once, and it was before I understood it was a delibarate convention.

As a kind of fun side note, our first interaction seems to have been on more or less this topic, 5 years ago! 
https://groups.google.com/d/msg/sage-devel/1gPkeL_X5dw/rKRglDI8n1gJ

**Comment by fieker** [comment]
Careful: base_ring is not a mathematical concept, so relying on it for anything is dangerous.
base_ring is ONLY a refelction of the implementation. If you need methematics, hope for coefficient_ring/field (which is present sometimes)

**Comment by rfourquet** [comment]
> If you need methematics, hope for coefficient_ring/field (which is present sometimes)

I do hope for `coefficient_ring` :) 
For practical purpose, I often consider `base_ring` to mean `coefficient_ring`, as the docstring for it often says "Return the base (coefficient) ring of ...", but indeed the fact that it's "ONLY a reflection of the implementation" makes it hard to reason about.

File: src/generic/LaurentSeries.jl (hunk 2 above)
Comment (wbhart) [reply src/generic/LaurentSeries.jl]: I remember that discussion, though I hadn't remembered it was you that replied to me there. I did remember Robert being so disappointed at my hack!

Anyway, clearly we disagree on some things not germane to this PR and we should at least discuss them elsewhere (IRL). I hope that you don't really feel patronised. I will always interpret a suggestion to follow a convention as an invitation to make the change everywhere. Otherwise it isn't a convention and I won't enforce it.

In any case, my bad. I should not have used the word convention here. We do not have any convention on this issue. What I should have said is, "it has been a common practice". So I apologise if I made more out of this than should have been.

Having said that, this is not a change we support, so I won't make the change here either. I appreciate that I misunderstood your motivations here, and I do appreciate you making suggestions. Please accept my apology for making more of this than I should have.

Comment (wbhart) [reply src/generic/LaurentSeries.jl]: By the way, is there anything else remaining which is germane to the PR that I haven't sorted yet. It would be nice to be able to merge the PR.

File: src/generic/RelSeries.jl (hunk 7 above)
Comment (wbhart) [reply src/generic/RelSeries.jl]: There's no need to define characteristic for ^ to work. I structured the PR so that it won't give incorrect answers. You get the result faster if you can use pow_fps. But you can only use that if you have char 0. There are many rings for which you can't decide the characteristic.

The suggestion to have:

characteristic(S) = characteristic(coefficient_ring(S))

for both polynomial rings and series has been discussed with @fieker, and I believe we agree we can do this. That's much more mathematically meaningful and it will resolve the current inefficiency in some cases. But it's a separate PR. I'll now open a ticket for it. (Naturally there is already a lot to do to roll the current thing out across all our packages.)

Comment (rfourquet) [reply src/generic/RelSeries.jl]: > There's no need to define characteristic for ^ to work

Ah sure, sorry I got confused about that.

Otherwise yes, this plan sounds good. I will review once more now to help have this merged fast.

File: src/generic/MPoly.jl [hunk 8]
```diff
@@ -2409,11 +2427,14 @@ function ^(a::MPoly{T}, b::Int) where {T <: RingElement}
...
       return parent(a)([coeff(a, 1)^b], exps)
    elseif b == 0
-      return parent(a)(1)
+      return one(a)
    elseif b == 1
-      return a
+      return deepcopy(a)
    elseif b == 2
       return a*a
+   elseif characteristic(base_ring(a)) != 0
```
Comment (rfourquet) [inline src/generic/MPoly.jl]: This won't work if the characteristic is `missing`, as `missing != 0` is equal to `missing`, which is not allowed in a condition. You must write something like `if coalesce(characteristic(base_ring(a)), -1) != 0`.

Comment (rfourquet) [reply src/generic/MPoly.jl]: I will look into adding a test for that, with a ring which uses the `missing` fallback.

File: src/generic/Residue.jl [hunk 9]
```diff
@@ -126,6 +126,10 @@ end
 deepcopy_internal(a::AbstractAlgebra.ResElem, dict::IdDict) =
    parent(a)(deepcopy(data(a)))
 
+function characteristic(a::ResRing{T}) where T <: Integer
```
Comment (rfourquet) [inline src/generic/Residue.jl]: Should'nt it be
```suggestion
function characteristic(a::ResRing{T}) where T <: RingElement
```
?

File: src/generic/MPoly.jl (hunk 8 above)
Comment (rfourquet) [reply src/generic/MPoly.jl]:
```suggestion
   elseif coalesce(characteristic(base_ring(a)), -1) != 0
```
Made a "code suggestion" to make it easier to include.

Comment (wbhart) [reply src/generic/MPoly.jl]: This seems to be equivalent to just returning -1 instead of missing, which would be a lot simpler. I think I will do that, as this seems to be a lot messier in comparison. Of course, -1 cannot be a valid characteristic and it can just stand for "don't know".

File: src/generic/Residue.jl (hunk 9 above)
Comment (wbhart) [reply src/generic/Residue.jl]: No. What I have is correct. You cannot determine the characteristic in general, only when you have an integer.

File: src/generic/MPoly.jl (hunk 8 above)
Comment (rfourquet) [reply src/generic/MPoly.jl]: Yes I agree, `missing` is a more explicit sentinel, hence my earlier suggestion, but it's simple `-1`. The drawback is that the code might silently fail if we forget to check against `-1`, but tests should help. Plus, it's internal only (for the moment) so we don't need to think too much about the long term consequences of this choice.

File: src/generic/Residue.jl (hunk 9 above)
Comment (rfourquet) [reply src/generic/Residue.jl]: Oh sorry, I must have forgotten to think.

File: src/generic/LaurentSeries.jl (hunk 2 above)
Comment (rfourquet) [reply src/generic/LaurentSeries.jl]: Thanks for your comprehension. I must admit that I still don't fully understand the subtlety with a "common practice" which is not really a convention but which must be consistent. But I totally agree we should discuss these not-germane-to-the-PR things directly IRL, if/when needed.

Comment (wbhart) [reply src/generic/LaurentSeries.jl]: You understand correctly. A "convention" should be enforced. A "common practice" has not been and will not be unless we make a decision to make it a convention. I should not have used the word convention.

**Comment by rfourquet** [comment]
The `missing` stuff still needs fixing. Will you do that @wbhart? (I can if you like)
