### PR TITLE
Simplify `evaluate` for mpolys

### LINKED ISSUE #2371: Evaluate is sometimes broken for mpolys
I discovered this while working on #2364.

```
julia> R,(x,y,z)=QQ[:x,:y,:z]
(Multivariate polynomial ring in 3 variables over rationals, AbstractAlgebra.Generic.MPoly{Rational{BigInt}}[x, y, z])

julia> f=x+y+z
x + y + z

julia> evaluate(f, [1//2,x,3])
x + 7//2

julia> v=RingElement[1//2,x,3]
3-element Vector{RingElement}:
 1//2
   x
  3

julia> evaluate(f, v)
ERROR: MethodError: Cannot `convert` an object of type AbstractAlgebra.Generic.MPoly{Rational{BigInt}} to an object of type Rational{BigInt}
The function `convert` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number
   @ Base number.jl:6
  convert(::Type{T}, ::Number) where T<:Number
   @ Base number.jl:7
  convert(::Type{T}, ::T) where T
   @ Base Base_compiler.jl:133
  ...

Stacktrace:
 [1] push!(a::Vector{Rational{BigInt}}, item::AbstractAlgebra.Generic.MPoly{Rational{BigInt}})
   @ Base ./array.jl:1288
 [2] evaluate(a::AbstractAlgebra.Generic.MPoly{Rational{BigInt}}, vals::Vector{RingElement})
   @ AbstractAlgebra ~/.julia/packages/AbstractAlgebra/Ccm2Q/src/MPoly.jl:982
 [3] top-level scope
   @ REPL[9]:1
```

@thofma I believe that this is the error causing the HeckeCI failure in #2364. While fixing this issue should resolve the CI failure over there I also think that `points_with_x_coordinate` should be adjusted to call a more specific `evaluate` method by first converting all supplied values to a common parent.

### PR DESCRIPTION
**Pull request by SoongNoonien**
This fixes #2371. I'm not entirely sure if I made some stupid mistake here but previously the code was way more complex.
Note that this still has some weird effects because the parent ring is mostly determined by the first value:

```
julia> R,(x,y,z)=QQ[:x,:y,:z]
(Multivariate polynomial ring in 3 variables over rationals, AbstractAlgebra.Generic.MPoly{Rational{BigInt}}[x, y, z])

julia> evaluate(R(), RingElement[0,x,0])
0//1

julia> typeof(ans)
Rational{BigInt}

julia> evaluate(R(), RingElement[x,0,0])
0

julia> typeof(ans)
AbstractAlgebra.Generic.MPoly{Rational{BigInt}}

```

How do we want the code to behave in these types of situations.

Note that I haven't added any tests yet.

### CODE REVIEW

File: src/MPoly.jl [hunk 1]
```diff
@@ -979,19 +978,9 @@ function evaluate(a::MPolyRingElem{T}, vals::Vector{U}) where {T <: RingElement,
...
-      while iseven(j) && length(r) > 1
-          top = pop!(r)
-          r[end] = add!(r[end], top)
-          j >>= 1
-      end
-   end
-   while length(r) > 1
-      top = pop!(r)
-      r[end] = add!(r[end], top)
+      r = add!(r, c*t)
```
Comment (fingolfin) [inline src/MPoly.jl:981]: Upside: this is much simpler.
Downside: I *think* the old code was meant as an optimization, where we don't form the sum from left to right, but rather try to keep summands "of similar" size (assuming they were "of similar size" at the start). I.e. I think (but have not worked it out, just guessing from the shape of the code) that it tries to add the values at position 1 and 2; position 3 and 4; 5 and 6 etc.; and then (1+2)+(3+4) etc. -- i.e. it computes "balanced sums". This can be beneficial in some cases.

However, this function is the very last resort. Whether it is really beneficial to apply this kind of optimization here, I don't know.

On the other hand, if we have it and it works, we might as well keep it?

But I don't have any strong oppinion either way, plus my guess might be totally wrong. 

Perhaps @thofma or @fieker have thoughts / opinions on this.
