### PR TITLE
Fix handling of kwargs in @polynomial_ring

### LINKED ISSUE #1631: `@polynomial_ring` support for key-value pairs is broken
This works:
```
julia> polynomial_ring(QQ, ["x", "y"]; internal_ordering=:lex)
(Multivariate polynomial ring in 2 variables over rationals, AbstractAlgebra.Generic.MPoly{Rational{BigInt}}[x, y])
```
But the macro version does not:
```
julia> @polynomial_ring(QQ, ["x", "y"]; internal_ordering=:lex)
ERROR: LoadError: MethodError: no method matching popfirst!(::Tuple{Expr, Symbol, Expr})

Closest candidates are:
  popfirst!(::BitVector)
   @ Base bitarray.jl:868
  popfirst!(::BitSet)
   @ Base bitset.jl:276
  popfirst!(::AbstractChannel)
   @ Base channels.jl:11
  ...

Stacktrace:
 [1] var"@polynomial_ring"(__source__::LineNumberNode, __module__::Module, args::Vararg{Any})
   @ AbstractAlgebra ~/Projekte/OSCAR/AbstractAlgebra.jl/src/misc/VarNames.jl:293
in expression starting at REPL[40]:1
```

So it tries to `popfirst!` a macro, which of course doesn't work.

### PR DESCRIPTION
**Pull request by fingolfin**
Resolves #1631 (was easier than I feared :-) )

### CODE REVIEW

**Comment by fingolfin** [comment]
@lgoettgens suggested how to improve the tests, which I now did

File: test/generic/MPoly-test.jl [hunk 1]
```diff
@@ -140,6 +140,17 @@
    QQxxx3 = @polynomial_ring(QQ, :x=>1:3)
    @test QQxxx_ == (QQxxx3, [x1, x2, x3])
 
+   # test support of kwargs
+   QQxxx4 = @polynomial_ring(QQ, "x#" => 1:3; internal_ordering=:lex)
+   @test QQxxx_ == (QQxxx4, [x1, x2, x3])
+
+   QQxxx_deglex_ = @inferred polynomial_ring(QQ, "x#" => 1:3; internal_ordering=:deglex)
+   @test QQxxx_deglex_[1].ord == :deglex
```
Comment (lgoettgens) [inline test/generic/MPoly-test.jl:148]:
```suggestion
   @test internal_ordering(QQxxx_deglex_[1]) == :deglex
```

File: test/generic/MPoly-test.jl [hunk 2]
```diff
@@ -140,6 +140,17 @@
...
+
+   QQxxx_deglex2 = @polynomial_ring(QQ, "x#" => 1:3; internal_ordering=:deglex)
+   @test QQxxx_deglex2.ord == :deglex
```
Comment (lgoettgens) [inline test/generic/MPoly-test.jl:151]:
```suggestion
   @test internal_ordering(QQxxx_deglex2) == :deglex
```

File: test/generic/MPoly-test.jl [hunk 3]
```diff
@@ -140,6 +140,17 @@
    QQxxx3 = @polynomial_ring(QQ, :x=>1:3)
    @test QQxxx_ == (QQxxx3, [x1, x2, x3])
 
+   # test support of kwargs
+   QQxxx4 = @polynomial_ring(QQ, "x#" => 1:3; internal_ordering=:lex)
```
Comment (lgoettgens) [inline test/generic/MPoly-test.jl:144]: Why did you change the symbol from `:x` to `x#`?

Comment (fingolfin) [reply test/generic/MPoly-test.jl:144]: So that I can directly compare the result of `polynomial_ring` and `@polynomial_ring`: the former turns `:x => 1:3` into variable `x[1]` etc., the latter into `x1`, etc.

**Review by lgoettgens — APPROVED** [review]
