### PR TITLE
Hopefully fix unicodes and indented pretty printing

### LINKED ISSUE #1561: Pretty printing code (esp. indent) has issues with non-ASCII unicode strings
While adding indentation to some printing code that prints some non-ASCII text (here: a "wedge" symbol), I run into this error (I'd try to produce a minimal reproducer, but I don't have time right now, and at least don't want to forget about this; but it shouldn't be hard to generate another, just write a `show` method printing a bunch of `ä` or whatnot and then indent-print it?)
```
│   exception =
│    StringIndexError: invalid index [14], valid nearby indices [12]=>'∧', [15]=>'e'
│    Stacktrace:
│      [1] string_index_err(s::String, i::Int64)
│        @ Base ./strings/string.jl:12
│      [2] SubString{String}(s::String, i::Int64, j::Int64)
│        @ Base ./strings/substring.jl:35
│      [3] SubString
│        @ ./strings/substring.jl:41 [inlined]
│      [4] SubString
│        @ ./strings/substring.jl:47 [inlined]
│      [5] SubString
│        @ ./strings/substring.jl:43 [inlined]
│      [6] getindex
│        @ ./strings/substring.jl:281 [inlined]
│      [7] _write_line(io::AbstractAlgebra.PrettyPrinting.IOCustom{IOContext{IOBuffer}}, str::SubString{String})
│        @ AbstractAlgebra.PrettyPrinting ~/.julia/packages/AbstractAlgebra/R29qD/src/PrettyPrinting.jl:1595
│      [8] write(io::AbstractAlgebra.PrettyPrinting.IOCustom{IOContext{IOBuffer}}, str::String)
│        @ AbstractAlgebra.PrettyPrinting ~/.julia/packages/AbstractAlgebra/R29qD/src/PrettyPrinting.jl:1634
│      [9] print(io::AbstractAlgebra.PrettyPrinting.IOCustom{IOContext{IOBuffer}}, s::String)
│        @ Base ./strings/io.jl:246
```

The problem is that in a non-ASCII string, not every index is valid, but the code in `_write_line(io::IOCustom, str::AbstractString)` implicitly assumes this can be done. The crash is here:
```julia
...
  firstlen = min(spaceleft, length(str))
  firststr = str[1:firstlen]  # <-- here
...
```
What we really want to do is to take the first couple "graphemes" (?), not bytes in the string. Perhaps using [`Unicode.graphemes`](https://docs.julialang.org/en/v1/stdlib/Unicode/#Unicode.graphemes) would be a way to resolve this. Dunno.

### PR DESCRIPTION
**Pull request by aaruni96**
Fixes #1561

### CODE REVIEW

**Comment by thofma** [comment]
Thanks. I would like to see a bit more tests, things with non-standard width like '⛵' and where it has to wrap a line.

**Comment by aaruni96** [comment]
Fixed the case where the spilled over line still had unicode.

Now looking into characters with non standard widths.

**Review by lgoettgens — APPROVED** [review]
Not getting weird errors from unicode chars getting ripped in half is already a great step IMO.
handling chars of different widths and still get visually a fixed with of x columns in the terminal is great to have, but I think much harder to implement. Thus I would be happy to merge as is (with a few more tests) and get everything else in a future PR.

**Comment by fingolfin** [comment]
I agree 100% with @lgoettgens . I have zero issues with printing involving double width chars right now, but I've run into errors due to multibyte single width chars in two completely independent situations by now.

File: src/PrettyPrinting.jl [hunk 1]
```diff
@@ -1592,7 +1592,14 @@ function _write_line(io::IOCustom, str::AbstractString)
   end
   #@show spaceleft
   firstlen = min(spaceleft, length(str))
-  firststr = str[1:firstlen]
+  # make an iterator over valid indices
+  firstiter = Base.Iterators.take(eachindex(str), firstlen)
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1596]: I don't think this will handle combiners correctly (as often used for accents, e.g. in `í` unless normalized to latin).

Comment (fingolfin) [reply src/PrettyPrinting.jl:1596]: Actually if I enter this via copy&paste on my mac it works as it is normalized, but if I do `"i\acute<TAB>"` I get it:
```
julia> s = "í"
"í"

julia> collect(eachindex(s))
1-element Vector{Int64}:
 1

julia> s = "í"  # looks the same but isn't the same on a byte level
"í"

julia> collect(eachindex(s))
2-element Vector{Int64}:
 1
 2
```

File: src/PrettyPrinting.jl [hunk 2]
```diff
@@ -1592,7 +1592,14 @@ function _write_line(io::IOCustom, str::AbstractString)
...
+  restiter = Base.Iterators.drop(eachindex(str), firstlen)
+  firststr = ""
+  reststr = ""
+  for index in firstiter
+   firststr *= str[index]
+  end
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1602]: Maybe like this
```suggestion
  firststr = str[collect(firstiter)]
```

File: src/PrettyPrinting.jl (hunk 1 above)
Comment (lgoettgens) [reply src/PrettyPrinting.jl:1596]: I think this can be circumvented by https://docs.julialang.org/en/v1/stdlib/Unicode/#Unicode.normalize

File: src/PrettyPrinting.jl [hunk 3]
```diff
@@ -1601,13 +1608,18 @@ function _write_line(io::IOCustom, str::AbstractString)
...
   it = Iterators.partition(1:textwidth(reststr), c - ind > 0 ? c - ind : c)
   for i in it
-    written += write(io.io, "\n")
-    written += write_indent(io)
-    written += write(io.io, reststr[i])
-    io.printed = textwidth(reststr[i])
+   written += write(io.io, "\n")
+   written += write_indent(io)
+   for j in Base.Iterators.drop(Base.Iterators.take(str,i[end]), i[begin]-1)
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1618]: probably would be helpful to insert a comment explaining what's going on here...

File: src/PrettyPrinting.jl (hunk 1 above)
Comment (fingolfin) [reply src/PrettyPrinting.jl:1596]: For tests might be best to store the "bad" characters as byte sequences so we are sure that we are testing the right ones
```
julia> s = "í"
"í"

julia> Vector{UInt8}(s)
2-element Vector{UInt8}:
 0xc3
 0xad

julia> String(Vector{UInt8}(s))
"í"
```

**Comment by lgoettgens** [comment]
I think most of this could be written very nice and concise using the second dispatch (with UnitRange) of https://docs.julialang.org/en/v1/stdlib/Unicode/#Unicode.graphemes, but unfortunately this is only existent from julia 1.9. So maybe add a comment referencing this so we can rewrite once the compat bound is changed. Or we include the function for older versions ourselves

File: src/PrettyPrinting.jl (hunk 1 above)
Comment (fingolfin) [reply src/PrettyPrinting.jl:1596]: These are the characters that made me notice the issue:
```
julia> Vector{UInt8}("∧")
3-element Vector{UInt8}:
 0xe2
 0x88
 0xa7

julia> Vector{UInt8}("…")
3-element Vector{UInt8}:
 0xe2
 0x80
 0xa6
```

The latter e.g. with `orbits(symmetric_group(50))` (works for smaller values than 21 for me -- may depend on your terminal settings)

Comment (aaruni96) [reply src/PrettyPrinting.jl:1596]: This should be fixed by normalizing everything before use, right ?

File: src/PrettyPrinting.jl (hunk 3 above)
Comment (aaruni96) [reply src/PrettyPrinting.jl]: I've added some comments, not sure how useful they are. (Right now, in my mind, it is obvious what is going on, and I am having difficulty coming up with an explanation....)

**Comment by aaruni96** [comment]
I've found a strange bug already, while trying to write a test. Please do not merge this in its current state.

**Comment by fingolfin** [comment]
I marked this as a "draft" PR for now :-)

File: src/PrettyPrinting.jl [hunk 4]
```diff
@@ -1591,8 +1591,14 @@ function _write_line(io::IOCustom, str::AbstractString)
     spaceleft = c - ind - io.printed
   end
   #@show spaceleft
-  firstlen = min(spaceleft, length(str))
-  firststr = str[1:firstlen]
+  # maybe rewrite using https://docs.julialang.org/en/v1/stdlib/Unicode/#Unicode.graphemes
+  # once minimum supported version for package is Julia 1.9
+  normalised_str = Base.Unicode.normalize(str)
```
[the remark this answers is not in the document]
Comment (lgoettgens) [reply src/PrettyPrinting.jl:1596]: Yeah, I think the cleanest solution would be to copy the UnitRange dispatch of grapheme from base into AA (dependent on the julia version) and use that

[the remark this answers is not in the document]
Comment (fingolfin) [reply src/PrettyPrinting.jl:1596]: But why do we even need the range dispatch?! Just use the single arg version and split the result at the right place? That would also get rid of the iterator shenanigans

[the remark this answers is not in the document]
Comment (lgoettgens) [reply src/PrettyPrinting.jl:1596]: You're right

[the remark this answers is not in the document]
Comment (aaruni96) [reply src/PrettyPrinting.jl]: Sorry it took so long to fix again. `graphemes` still returns an iterator, and until sometime ago, I was unaware that you can use `join(collect())` to make a string out of an iterator.

(Surprisingly, "julia join character array to string" did not lead to this answer, but "julia concatenate character array to string" did...)

File: src/PrettyPrinting.jl [hunk 5]
```diff
@@ -1591,8 +1591,14 @@ function _write_line(io::IOCustom, str::AbstractString)
     spaceleft = c - ind - io.printed
   end
   #@show spaceleft
-  firstlen = min(spaceleft, length(str))
-  firststr = str[1:firstlen]
+  # maybe rewrite using https://docs.julialang.org/en/v1/stdlib/Unicode/#Unicode.graphemes
+  # once minimum supported version for package is Julia 1.9
```
Comment (lgoettgens) [inline src/PrettyPrinting.jl:1595]:
```suggestion
```
you already use graphemes

**Review by lgoettgens — COMMENTED** [review]
The code changes look very clean now after the refactoring. Thanks!

Whats left from the comments above: Can you add some tests using something with many combiners (like in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1581#discussion_r1472082746) and something of non-standard width (like in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1581#issuecomment-1914714296)?

**Comment by aaruni96** [comment]
No longer crashes when graphemes of non standard width are encountered, but currently does not account for it while calculating when to line break.

I will add tests including wide graphemes along with the patch that makes them print in line with other characters.

File: src/PrettyPrinting.jl [hunk 6]
```diff
@@ -1591,23 +1591,89 @@ function _write_line(io::IOCustom, str::AbstractString)
...
-  firststr = str[1:firstlen]
-  if io.lowercasefirst
-    written += write(io.io, lowercasefirst(firststr))
-    io.lowercasefirst = false
+  _graphemes = Base.Unicode.graphemes(str)
+  firstlen = min(spaceleft, length(_graphemes))
+  # make an iterator over valid indices
+  firstiter = Base.Iterators.take(_graphemes, firstlen)
+  restiter = Base.Iterators.drop(_graphemes, firstlen)
+  firststr = join(firstiter)
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1599]: Could it be that an uppercase character has a different width than a lower case character? I hope not, but maybe it is safer to todo
```suggestion
  firststr = join(firstiter)
  if io.lowercasefirst
    firststr = lowercasefirst(firststr)
    io.lowercasefirst = false
  end
```
and then all lowercase treatment afterwards can go away

File: src/PrettyPrinting.jl [hunk 7]
```diff
@@ -1591,23 +1591,89 @@ function _write_line(io::IOCustom, str::AbstractString)
...
+      written += write(io.io, printstr)
+      io.lowercasefirst = false
+    end
+    io.printed += textwidth(printstr)
+  end
+  it = Iterators.partition(1:length(restiter), c - ind > 0 ? c - ind : c)
+  for i in it
+    # partitions of the spillover text
+    partcollect = collect(restiter)[i]
+    partstr = join(collect(restiter)[i])
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1645]: Doing `collect(restiter)` in each loop iteration (and twice at that!) will each time allocate a new `Vector`. Better to do it once before the loop
```suggestion
  rest = collect(restiter)
  for i in it
    # partitions of the spillover text
    partcollect = rest[i]
    partstr = join(rest[i])
```

File: src/PrettyPrinting.jl [hunk 8]
```diff
@@ -1591,23 +1591,89 @@ function _write_line(io::IOCustom, str::AbstractString)
...
+    if (textwidth(partstr) < (c - ind > 0 ? c - ind : c)) || length(i) == textwidth(partstr)
+      written += write(io.io, "\n")
+      written += write_indent(io)
+      written += write(io.io, partstr)
+      io.printed = textwidth(partstr)
+      println()
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1651]:
```suggestion
      println(io)
```

File: src/PrettyPrinting.jl [hunk 9]
```diff
@@ -1591,23 +1591,89 @@ function _write_line(io::IOCustom, str::AbstractString)
...
+         j += 1
+         if j > length(partcollect)
+            break
+         end
+      end
+      written += write(io.io, "\n")
+      written += write_indent(io)
+      written += write(io.io, printstr)
+      io.printed = textwidth(printstr)
+      println()
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1669]:
```suggestion
      println(io)
```
I am surprised your tests didn't catch this, perhaps they need to be refined to handle this?

File: src/PrettyPrinting.jl [hunk 10]
```diff
@@ -1591,23 +1591,89 @@ function _write_line(io::IOCustom, str::AbstractString)
     spaceleft = c - ind - io.printed
   end
   #@show spaceleft
-  firstlen = min(spaceleft, length(str))
-  firststr = str[1:firstlen]
-  if io.lowercasefirst
-    written += write(io.io, lowercasefirst(firststr))
-    io.lowercasefirst = false
+  _graphemes = Base.Unicode.graphemes(str)
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1594]:
```suggestion
  # The following code deals with line wrapping of Unicode text, including
  # double-width symbols and more.
  _graphemes = Base.Unicode.graphemes(str)
```

File: src/PrettyPrinting.jl [hunk 11]
```diff
@@ -1591,23 +1591,89 @@ function _write_line(io::IOCustom, str::AbstractString)
...
+  firstlen = min(spaceleft, length(_graphemes))
+  # make an iterator over valid indices
+  firstiter = Base.Iterators.take(_graphemes, firstlen)
+  restiter = Base.Iterators.drop(_graphemes, firstlen)
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1598]: is this still necessary? isn't `_graphemes` a simple `Vector`? Then perhaps this also works:
```suggestion
  firstiter = _graphemes[1:firstlen]
  restiter = _graphemes[firstlen+1:end]
```

And then you could rename `firstiter` and `restiter` and further simplify some code using them (e.g. `collect` on them now would be redundant)

**Review by fingolfin — COMMENTED** [review]
Just had a quick look. The `println(io)` bit must be changed. I think the `lowercasefirst` handling should also be changed then as we need to re-run tests anyway, and it simplifies the code. Your choice about the iterators

File: src/PrettyPrinting.jl (hunk 11 above)
Comment (aaruni96) [reply src/PrettyPrinting.jl:1598]: No, unfortunately `_graphemes` is an iterator.

`graphemes(s::AbstractString) -> GraphemeIterator` ( https://docs.julialang.org/en/v1/stdlib/Unicode/#Unicode.graphemes )

File: src/PrettyPrinting.jl (hunk 9 above)
Comment (aaruni96) [reply src/PrettyPrinting.jl:1669]: I added a stray `println(io)` at some point, and just removed the `io` instead of removing the entire line when the tests complained... Fixed now.

File: src/PrettyPrinting.jl [hunk 12]
```diff
@@ -1591,23 +1591,81 @@ function _write_line(io::IOCustom, str::AbstractString)
     spaceleft = c - ind - io.printed
   end
   #@show spaceleft
-  firstlen = min(spaceleft, length(str))
-  firststr = str[1:firstlen]
+  # The following code deals with line wrapping of Unicode text, including
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1594]: Can't we just do this at the start and then remove the last lowercase bits afterwards?
```suggestion
  if io.lowercasefirst
    str = lowercasefirst(str)
    io.lowercasefirst = false
  end 
  # The following code deals with line wrapping of Unicode text, including
```

File: src/PrettyPrinting.jl [hunk 13]
```diff
@@ -1591,23 +1591,81 @@ function _write_line(io::IOCustom, str::AbstractString)
...
   end
-  io.printed += textwidth(firststr)
-  reststr = str[firstlen + 1:end]
-  it = Iterators.partition(1:textwidth(reststr), c - ind > 0 ? c - ind : c)
-  for i in it
+  restiter = Base.Iterators.drop(_graphemes, firstlen)
+  firststr = join(firstiter)
+  if length(firstiter) == textwidth(firststr)
+    written += write(io.io, firststr)
+    io.printed += textwidth(firststr)
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1612]: Computing `textwidth` is not free, so maybe remember the result?
```suggestion
  width = textwidth(firststr)
  if length(firstiter) == width
    written += write(io.io, firststr)
    io.printed += width
```
I guess would could also use `length(firststr)` (which I think at this point is equal to `length(firstiter)` and hence `textwidth(firststr)` but an explicit `width` seems clearer?)

File: src/PrettyPrinting.jl [hunk 14]
```diff
@@ -1591,23 +1591,81 @@ function _write_line(io::IOCustom, str::AbstractString)
...
+  else
+    #firstline is wider than number of graphemes
+    partcollect = collect(firstiter)
+    printstr = ""
+    j = 1
+    while textwidth(printstr) < (c - ind > 0 ? c - ind : c)
+      printstr *= partcollect[j]
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1619]: Note that this is essentially a quadratic algorithm now that could be linear (luckily bounded by the terminal width), because `textwidth` is called on longer and longer strings. 
```suggestion
    j = 1
    width = 0
    while width < (c - ind > 0 ? c - ind : c)
      printstr *= partcollect[j]
      width += textwidth(partcollect[j])
```

File: src/PrettyPrinting.jl [hunk 15]
```diff
@@ -1591,23 +1591,81 @@ function _write_line(io::IOCustom, str::AbstractString)
...
+      j += 1
+      if j > length(partcollect)
+        break
+      end
+    end
+    written += write(io.io, printstr)
+    io.printed += textwidth(printstr)
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1626]:
```suggestion
    io.printed += width
```

File: src/PrettyPrinting.jl [hunk 16]
```diff
@@ -1591,23 +1591,81 @@ function _write_line(io::IOCustom, str::AbstractString)
...
+    #the spillover string
     written += write(io.io, "\n")
     written += write_indent(io)
-    written += write(io.io, reststr[i])
-    io.printed = textwidth(reststr[i])
+    printstr = join(collect(firstiter)[j:end])
+    written += write(io.io, printstr)
+    io.printed += textwidth(printstr)
+  end
+  it = Iterators.partition(1:length(restiter), c - ind > 0 ? c - ind : c)
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1635]: I think `c` and `ind` are constant, right? So how about setting `limit = c - ind > 0 ? c - ind : c` somewhere at the start of this patch, and then using that everywhere, instead of repeating this check? I think the resulting code will be clearer

File: src/PrettyPrinting.jl [hunk 17]
```diff
@@ -1591,23 +1591,81 @@ function _write_line(io::IOCustom, str::AbstractString)
...
+  restcollect = collect(restiter)
+  for i in it
+    # partitions of the spillover text
+    partcollect = restcollect[i]
+    partstr = join(partcollect)
+    if (textwidth(partstr) < (c - ind > 0 ? c - ind : c)) || length(i) == textwidth(partstr)
+      written += write(io.io, "\n")
+      written += write_indent(io)
+      written += write(io.io, partstr)
+      io.printed = textwidth(partstr)
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1645]:
```suggestion
    width = textwidth(partstr)
    if (width < (c - ind > 0 ? c - ind : c)) || length(i) == width
      written += write(io.io, "\n")
      written += write_indent(io)
      written += write(io.io, partstr)
      io.printed = width
```
or with `limit` available as suggested:
```suggestion
    width = textwidth(partstr)
    if width < limit || length(i) == width
      written += write(io.io, "\n")
      written += write_indent(io)
      written += write(io.io, partstr)
      io.printed = width
```

File: src/PrettyPrinting.jl [hunk 18]
```diff
@@ -1591,23 +1591,81 @@ function _write_line(io::IOCustom, str::AbstractString)
...
+         j += 1
+         if j > length(partcollect)
+            break
+         end
+      end
+      written += write(io.io, "\n")
+      written += write_indent(io)
+      written += write(io.io, printstr)
+      io.printed = textwidth(printstr)
+      printstr = join(partcollect[j:end])
```
Comment (fingolfin) [inline src/PrettyPrinting.jl:1663]:
```suggestion
      # print the second part (there are at most parts due to our assumption
      # that no grapheme exceeds double width)
      printstr = join(partcollect[j:end])
```

**Review by fingolfin — COMMENTED** [review]
Tests look good but there are a few simple optimizations to be had, see the code suggestions. Other than that I am OK with merging this. Feel free to come over to my office to discuss any of these.

**Review by fingolfin — APPROVED** [review]

**Comment by fingolfin** [comment]
Thanks @aaruni96 !!!
