### PR TITLE
Make Generic.MatSpace truly generic

### LINKED ISSUE #911: Matrix wrong parents
The following is difficult to fix, but disturbing nonetheless:

```
julia> using AbstractAlgebra

julia> S = MatrixSpace(ZZ, 2, 2; cached=false)
Matrix Space of 2 rows and 2 columns over Integers

julia> N = S()
[0   0]
[0   0]

julia> parent(N) == S
false
```

### LINKED ISSUE #974: Make nrows/ncols of a matrix optional
@rfourquet suggested:

> If nrows becomes part of the required interface for matrix space, maybe it could become optional for matrices? The fallback definition could be nrows(matrix) = nrows(parent(matrix)), although it would be slow in some cases, in particular when the parent is not in the field of the matrix and is created on demand.

### PR DESCRIPTION
**Pull request by fingolfin**
Closes #974
Resolves #911

### CODE REVIEW

File: src/generic/Matrix.jl [hunk 1]
```diff
@@ -10,16 +10,16 @@
 #
 ###############################################################################
 
-parent_type(::Type{S}) where {T <: NCRingElement, S <: Mat{T}} = MatSpace{T}
+parent_type(::Type{<:MatElem{T}}) where {T <: NCRingElement} = MatSpace{T, parent_type(T)}
 
-elem_type(::Type{MatSpace{T}}) where {T <: NCRingElement} = MatSpaceElem{T}
+elem_type(::Type{<:MatSpace{T}}) where {T <: NCRingElement} = dense_matrix_type(T)
```
Comment (lgoettgens) [inline src/generic/Matrix.jl:15]: If I am not mistaken, this would change `elem_type(Generic.MatSpace{QQFieldElem})` from `Generic.MatSpaceElem{QQFieldElem}` to `QQMatrix`. Is this intended?

Comment (thofma) [reply src/generic/Matrix.jl:15]: Yes. At the moment every matrix type implement its own matrix space type, like `QQMatrix` comes with `QQMatrixSpace`. All those "space" types do the same. They just store `nrows`, `ncols` and the `base_ring`. So the idea is to replace all those individual types by a truly generic "space" type.

File: src/generic/GenericTypes.jl [hunk 2]
```diff
@@ -1038,17 +1038,22 @@ const NCRingElement = Union{NCRingElem, RingElement}
 abstract type Mat{T} <: MatElem{T} end
 
 # not really a mathematical ring
-struct MatSpace{T <: NCRingElement} <: AbstractAlgebra.MatSpace{T}
+struct MatSpace{CoeffT, RingT} <: AbstractAlgebra.MatSpace{CoeffT}
```
Comment (fingolfin) [inline src/generic/GenericTypes.jl:1041]: Strictly speaking the introduction of the second type parameter `RingT` is not necessary for this PR, it just improves type stability, and I saw no harm in doing it?

I dropped the `<: NCRingElement` because `AbstractAlgebra.MatSpace{T}` already enforces it

File: src/generic/GenericTypes.jl [hunk 3]
```diff
@@ -1073,7 +1078,10 @@ end
 
 # construct zero matrix
 function MatSpaceElem{T}(R::NCRing, r::Int, c::Int) where T <: NCRingElement
-   entries = fill(zero(R), r, c)
+   entries = Matrix{T}(undef, r, c)
+   for i in 1:r*c
+      entries[i] = zero(R)
```
Comment (fingolfin) [inline src/generic/GenericTypes.jl:1083]: Note: this is actually a bug fix, so even if we reject this PR here, this part of it should be merged... The bug is that by aliasing some entries, some code won't work right if it uses functions like `add!` on matrix entries... I found out because this PR now uses this constructor, so the issue became apparent; in `master` it lurks hidden.

File: src/generic/Matrix.jl [hunk 4]
```diff
@@ -157,63 +159,44 @@ end
...
-   R = base_ring(a)
-   entries = Array{T}(undef, a.nrows, a.ncols)
-   for i = 1:a.nrows
-      for j = 1:a.ncols
-         entries[i, j] = zero(R)
-      end
-   end
-   z = MatSpaceElem{T}(R, entries)
-   return z
+   return dense_matrix_type(T)(base_ring(a), nrows(a), ncols(a))
```
Comment (fingolfin) [inline src/generic/Matrix.jl:164]: So the idea is that every matrix type should provide at least one constructor with signature `R::NCRing, r::Int, c::Int` which produces a zero matrix, and we define everything else in terms of that. (Of course additional such methods can be installed for specific matrix types as an optimization; but the generic code always first creates a zero matrix and then adjusts its entries as needed)

File: src/generic/Matrix.jl [hunk 5]
```diff
@@ -157,63 +159,44 @@ end
...
+# convert a Julia matrix
+function (a::MatSpace{T})(b::AbstractMatrix{S}) where {T <: NCRingElement, S}
+   _check_dim(nrows(a), ncols(a), b)
    R = base_ring(a)
-   _check_dim(a.nrows, a.ncols, b)
-   if !isempty(b)
-      R != parent(b[1, 1]) && error("Unable to coerce matrix")
+
+   # minor optimization for MatSpaceElem
+   if S === T && dense_matrix_type(T) === MatSpaceElem{T} && all(x -> R == parent(x), b)
```
Comment (fingolfin) [inline src/generic/Matrix.jl:184]: This `all(x -> R == parent(x), b)` was not there before -- instead we only checked the parent of `b[1,1]` and somehow hoped that's enough... Of course this check makes things a bit slower, but also safer...

**Comment by fingolfin** [comment]
This is now ready to review.

File: src/generic/GenericTypes.jl (hunk 3 above)
Comment (thofma) [reply src/generic/GenericTypes.jl:1083]: Yes, the code in AA assumes that one cannot do `add!` on matrix entries per se. If we want to change this, this needs further discussion and maybe do it in a separate PR.

File: src/generic/Matrix.jl (hunk 5 above)
Comment (thofma) [inline src/generic/Matrix.jl:184]:
```suggestion
   if S === T && dense_matrix_type(T) === MatSpaceElem{T} && all(x -> R === parent(x), b)
```

File: src/generic/Matrix.jl [hunk 6]
```diff
@@ -222,9 +205,6 @@ end
 #
 ###############################################################################
 
-function matrix_space(R::AbstractAlgebra.NCRing, r::Int, c::Int; cached::Bool = true)
-   # TODO: the 'cached' argument is ignored and mainly here for backwards compatibility
-   # (and perhaps future compatibility, in case we need it again)
-   T = elem_type(R)
-   return MatSpace{T}(R, r, c)
+function matrix_space(R::AbstractAlgebra.NCRing, r::Int, c::Int)
```
Comment (fingolfin) [inline src/generic/Matrix.jl:208]: I think it is fine to remove the `cached` kwarg for `AA.Generic.matrix_space`.

But I wonder if we should bring it back for `AA. matrix_space` (it was removed in a prior PR, I think) for improved backwards compatibility with existing code calling it? (I guess technically if we don't do that, then this here is a breaking change)

File: src/generic/GenericTypes.jl (hunk 3 above)
Comment (fingolfin) [reply src/generic/GenericTypes.jl:1083]: So are you saying that code I found which failed when I aliased the zeros is wrong?

Otherwise, that link says that matrix elements may alias; but it does not prescribe whether e.g. `zero_matrix` may produce a matrix with aliased entries; or whether it perhaps *must* produce one with non-aliased entries?

For now I went with the latter because it fixed a bug, and it also preserves the current behavior, so is less likely to introduce regressions.

Comment (thofma) [reply src/generic/GenericTypes.jl:1083]: Yes, it is probably wrong. But I would have to see it.

File: src/generic/Matrix.jl [hunk 7]
```diff
@@ -157,63 +159,44 @@ end
...
-   for i = 1:a.nrows
-      for j = 1:a.ncols
-         if i != j
-            entries[i, j] = zero(R)
-         else
-            entries[i, j] = rb
-         end
-      end
+   for i in 1:min(nrows(a), ncols(a))
+      M[i, i] = rb
```
Comment (fingolfin) [inline src/generic/Matrix.jl:173]: of course here we also have aliased entries...

File: src/generic/GenericTypes.jl (hunk 2 above)
Comment (fingolfin) [reply src/generic/GenericTypes.jl:1041]: Why would it make everything slow? Note that `CoeffT` uniquely determines `RingT` and vice versa, so it's not as if we'd be creating additional specializations, would we? What am I missing?

File: src/generic/GenericTypes.jl (hunk 3 above)
Comment (thofma) [reply src/generic/GenericTypes.jl:1083]: Hm, maybe the same error as in https://github.com/Nemocas/AbstractAlgebra.jl/pull/955 :) There Claus made things also correct according to the documentation, but it exposed some other bugs.

I will have a look

File: src/generic/GenericTypes.jl (hunk 2 above)
Comment (thofma) [reply src/generic/GenericTypes.jl:1041]: Sorry, I should have written more. I was thinking of things like
```
x = Vector{MatSpace{T}}()
```
and
```
struct A
  x::MatSpace{T}
```
Do you also change it for the element? I don't understand why we would want to change this all of a sudden (in this PR here).

File: src/generic/GenericTypes.jl (hunk 3 above)
Comment (thofma) [reply src/generic/GenericTypes.jl:1083]: I wrote something about this proposed change in #1000

File: src/generic/GenericTypes.jl (hunk 2 above)
Comment (fingolfin) [reply src/generic/GenericTypes.jl]: I agree that this shouldn't be in this PR (if we do it at all). I've update the PR accordingly.

**Comment by fingolfin** [comment]
I've been wondering: right now, this PR is completely geared towards providing a unified `MatrixSpace` implementation for types returned by `dense_matrix_type(R)` for a given ring `R`. Which it does, and which is already simplifying things a lot for implementors.

But what if there are additional matrix types for the same ring `R`, e.g. sparse ones, or whatever else? Shouldn't these also have a matrix space parent? If yes, of course they are not worse off with this PR than without it. But we could extend things (in a future PR) to cover those types as well: if we made the matrix type a second type parameter for `struct Generic.MatSpace`, then we could handle those types as well. Thoughts?

**Comment by thofma** [comment]
I understand how this could be useful, but at the moment I do not see the end. For example, the sparse matrices are covered by https://github.com/thofma/Hecke.jl/blob/master/src/HeckeTypes.jl#L409. At the moment I do not see that we will have plenty of other matrix types, so I would put this on the back burner.

**Comment by fingolfin** [comment]
Yeah, it's not something I'd wish to tackle in this PR... and if we ever want it, it shouldn't be too hard to add.

Once the OscarCI woes are resolved (hoping PR #1345 will do that), I'll re-run CI here, and make sure all tests pass, and then I hope we can merge?

**Comment by fingolfin** [comment]
Re: unaliasing: so just to be clear, this is about restoring the behavior to how it was a few weeks ago: I changed it accidentally as a side effect of some other re-factoring.

If you think the accidental introducing of the aliasing I made is a desirable optimization, we can reintroduce it in a dedicated PR, together with similar changes to a bunch of other places where they could obviously be made. But it seems undesirable to have this kind of change as an accident in a commit / PR that does not even mention it (namely PR #1324). In particular this optimization is in 0.29.3 and 0.29.4 and in no other AA version.

**Comment by fingolfin** [comment]
I've removed the `fill` change / (un)aliasing change now. While I still think it was a mistake to introduce it "accidentally" in PR #1324 it seems equally problematic to remove it in this PR. Also doesn't seem worth our time to debate it overly here

**Comment by thofma** [comment]
OK. The downstream error is expected? If so, I will mark this as breaking

**Comment by fingolfin** [comment]
Better hold it for now, I may need to reconsider some things *sigh*

File: src/generic/Matrix.jl (hunk 6 above)
Comment (thofma) [reply src/generic/Matrix.jl:189]: I agree, that we should probably add it back and have it for "consistency"?

**Comment by thofma** [comment]
I added a comment on the `cached` question that came up. Apart from that, this looks good?

File: src/generic/Matrix.jl [hunk 8]
```diff
@@ -148,63 +148,44 @@ end
...
-   R = base_ring(a)
-   entries = Matrix{T}(undef, a.nrows, a.ncols)
-   for i = 1:a.nrows
-      for j = 1:a.ncols
-         entries[i, j] = zero(R)
-      end
-   end
-   z = MatSpaceElem{T}(R, entries)
-   return z
+   return zero_matrix(base_ring(a), nrows(a), ncols(a))::dense_matrix_type(T)
```
Comment (fingolfin) [inline src/generic/Matrix.jl:153]: So I was worried earlier: what if there is more than one "relevant" matrix type per ring?

One way to solve this would be to add a second type parameter to MatSpace indicating the matrix type, i.e.:
```
struct MatSpace{T <: NCRingElement, MatT}
```
then we can have a constructor which, `MatT` is omitted, sets it to `dense_matrix_type(T)`. Also `matrix_space(ring,r,c)` will use `dense_matrix_type(typeof(ring))` by default.

Then we can do
```
elem_type(::Type{MatSpace{T,MatT}}) where {T,MatT} = MatT
```
Finally, we need a clean way to instantiate a zero matrix of a given type (and base ring). We mandate that this must always work:
```
  new_zero_mat  =  MatT(ring, r, c)
```
and then we can redefine e.g. this function as
```
function (a::MatSpace{T,MatT})() where {T <: NCRingElement, MatT}
  MatT(base_ring(a), nrows(a), ncols(a))
end
```

**Comment by thofma** [comment]
We assume implictly at a lot of places that there is at most one matrix type for a ring type, so that `matrix_type -> base_ring_type -> matrix_type` is the identity. We need this to not litter our types with an endless redundant set of type parameters.

I am not super excited about mandatory constructors a la `MatT(...)` must exiat and must be the zero matrix. I guess I would rather prefer a `zero_matrix(::MatT, R, r, c)`, and `zero_matrix(R, r c) = zero_matrix(dense_matrix_type(R), R, r, c)`.

**Comment by fieker** [comment]
On Fri, Apr 26, 2024 at 01:12:15PM -0700, Max Horn wrote:
> @fingolfin commented on this pull request.
> 
> 
> 
> >  function (a::MatSpace{T})() where {T <: NCRingElement}
> -   R = base_ring(a)
> -   entries = Matrix{T}(undef, a.nrows, a.ncols)
> -   for i = 1:a.nrows
> -      for j = 1:a.ncols
> -         entries[i, j] = zero(R)
> -      end
> -   end
> -   z = MatSpaceElem{T}(R, entries)
> -   return z
> +   return zero_matrix(base_ring(a), nrows(a), ncols(a))::dense_matrix_type(T)
> 
> So I was worried earlier: what if there is more than one "relevant" matrix type per ring?
We have - everynow and then
 - lazy transpose
 - view
 - InjProj
 - vandermonde
 - sparse
> 
> One way to solve this would be to add a second type parameter to MatSpace indicating the matrix type, i.e.:
> ```
> struct MatSpace{T <: NCRingElement, MatT}
> ```
> then we can have a constructor which, `MatT` is omitted, sets it to `dense_matrix_type(T)`. Also `matrix_space(ring,r,c)` will use `dense_matrix_type(typeof(ring))` by default.
> 
> Then we can do
> ```
> elem_type(::Type{MatSpace{T,MatT}}) where {T,MatT} = MatT
> ```
> Finally, we need a clean way to instantiate a zero matrix of a given type (and base ring). We mandate that this must always work:
> ```
>   new_zero_mat  =  MatT(ring, r, c)
> ```
> and then we can redefine e.g. this function as
> ```
> function (a::MatSpace{T,MatT})() where {T <: NCRingElement, MatT}
>   MatT(base_ring(a), nrows(a), ncols(a))
> end

What is the natrual cosntructor for an not intialized matrix? A coompon
use case is allocate a matrix, fill it (ie. vcat, hcat) insisting in
having a well defined input matrix is wasteful...

**Comment by fieker** [comment]
On Fri, Apr 26, 2024 at 01:12:15PM -0700, Max Horn wrote:
> @fingolfin commented on this pull request.
> 
> 
> 
> >  function (a::MatSpace{T})() where {T <: NCRingElement}
> -   R = base_ring(a)
> -   entries = Matrix{T}(undef, a.nrows, a.ncols)
> -   for i = 1:a.nrows
> -      for j = 1:a.ncols
> -         entries[i, j] = zero(R)
> -      end
> -   end
> -   z = MatSpaceElem{T}(R, entries)
> -   return z
> +   return zero_matrix(base_ring(a), nrows(a), ncols(a))::dense_matrix_type(T)
> 
To me, an empty constructor was never guranteed to return a (valid)
zero. You want a zero, do (0) or zero...
Its fine if the initialisation is for free, but annoying if not.

**Comment by fieker** [comment]
On Sat, Apr 27, 2024 at 01:51:30AM -0700, Tommy Hofmann wrote:
> We assume implictly at a lot of places that there is at most one matrix type for a ring type, so that `matrix_type -> base_ring_type -> matrix_type` is the identity. We need this to not litter our types with an endless redundant set of type parameters.
> 
> I am not super excited about mandatory constructors a la `MatT(...)` must exiat and must be the zero matrix. I guess I would rather prefer a `zero_matrix(::MatT, R, r, c)`, and `zero_matrix(R, r c) = zero_matrix(dense_matrix_type(R), R, r, c)`.
I support that

**Comment by fingolfin** [comment]
So one the one hand, we 
> assume implictly at a lot of places that there is at most one matrix type for a ring type

but on the other hand we do have multiple other matrix types... One way to reconcile that would of course be to say "... but only matrix type per ring has a matrix_space". That's basically what the current state of this PR would go for. Which would be fine by me (less work for me, the PR basically could be merged as-is, I think).

**Comment by fingolfin** [comment]
Hrm, the tests against Nemo release fail because it has silly tests of the form
```
   m = one(Generic.MatSpace{Nemo.fpFieldElem}(Z13, 2, 2))
   for n = (m, -m, m*m, m+m, 2m)
      @test n isa Generic.MatSpaceElem{Nemo.fpFieldElem}
   end
```
which now fail because because the "generic" matspace and the regular matspace are the same.

I would still argue this does not constitute a true breaking change -- arguably that test is the problem, no real code relies on this.

**Review by lgoettgens — APPROVED** [review]

**Comment by lgoettgens** [comment]
I would argue that we should now export `MatSpace` both from `Generic` and `AbstractAlgebra` such that downstream one does not need to write `AbstractAlgebra.Generic.MatSpace` but just `MatSpace`

**Comment by lgoettgens** [comment]
> I would argue that we should now export `MatSpace` both from `Generic` and `AbstractAlgebra` such that downstream one does not need to write `AbstractAlgebra.Generic.MatSpace` but just `MatSpace`

Nevermind, this needs a breaking release since one needs to merge the abstract and the concrete type for this.

**Comment by lgoettgens** [comment]
> Hrm, the tests against Nemo release fail because it has silly tests of the form
> 
> ```
>    m = one(Generic.MatSpace{Nemo.fpFieldElem}(Z13, 2, 2))
>    for n = (m, -m, m*m, m+m, 2m)
>       @test n isa Generic.MatSpaceElem{Nemo.fpFieldElem}
>    end
> ```
> 
> which now fail because because the "generic" matspace and the regular matspace are the same.
> 
> I would still argue this does not constitute a true breaking change -- arguably that test is the problem, no real code relies on this.

I think that changing this behaviour would lead to https://github.com/Nemocas/Nemo.jl/issues/651 again. I didn't quite understand what'S going on there, but maybe @thofma remembers.

**Comment by thofma** [comment]
Yes, the tests are obsolete or wrong with the changes here (which we want!).

**Comment by lgoettgens** [comment]
The failures in HeckeCI seem like something real. Or do we want to abandon the kwarg `cached` for these?

**Comment by fingolfin** [comment]
On the long run the `cached` kwarg for `matrix_space` could go away as it now returns singletons anyway.

But the PR here does not actually remove a `cached` kwarg from `AbstractAlgebra.matrix_space`. Rather that was removed in PR #1313 from March 2023. But this was "hidden" because the custom matrix spaces in Nemo all came with custom `matrix_space` methods so we didn't notice...

As a pragmatic solution, I'll add back the `cached` kwarg here. Then once the dust has settled (i.e. this PR merged and released, and likewise its Nemo counterpart) we could remove its use(s) in Hecke, and at some point remove it again in a breaking PR from AA (of course that breaking PR could be open right away, no need to delay it)

**Comment by fingolfin** [comment]
The HeckeCI changes are resolved. Shall we merge this before making 0.41.4 then?

@thofma @lgoettgens

**Comment by lgoettgens** [comment]
For future bisecting/CI reasons, it would be better to first delete/adapt the tests in Nemo, release a new Nemo, then merge this, release a new AA, and then merge the rest in Nemo.

But if this is too much overhead and you are sure that https://github.com/Nemocas/Nemo.jl/pull/1738 can be merged immediately after releasing AA and fixes CI and everything, that's fine for me as well.

**Comment by lgoettgens** [comment]
> For future bisecting/CI reasons, it would be better to first delete/adapt the tests in Nemo, release a new Nemo, then merge this, release a new AA, and then merge the rest in Nemo.

I created https://github.com/Nemocas/Nemo.jl/pull/1748 to adapt the Nemo tests.

**Comment by lgoettgens** [comment]
> The HeckeCI changes are resolved. Shall we merge this before making 0.41.4 then?
> 
> @thofma @lgoettgens

Everything is green now. No objections from my side
