### PR TITLE
Fix issue with inflate modifying input.

### LINKED ISSUE #319: multiplication of Puiseux series modifies inplace
Here is an example:

```
using Nemo
CC = ComplexField(200);
R,x = PuiseuxSeriesRing(CC, 4, "x");
cs = [one(CC), zero(CC), one(CC), zero(CC)];
f = R(R.laurent_ring(cs, 4, 4, 0, 1, false), 2);
f
ff = f*f;
f
```

The reason for this is that inflate calls the constructor for Laurent series with rescale = true, and that one modifies in place via rescale! . The conceptual problem is that the constructor assumes that the coefficient vector is owned by noone else, but in the case of multiplication of Puiseux series it is. Since inflate (as opposed to inflate!) should not modify the vector, I think inflate should be adjusted. Alternatively, rename inflate to inflate! and send in a copy of the coefficient vector? Or inflate calls the constructor with rescale = false.

### PR DESCRIPTION
**Pull request by wbhart**
Closes #319

### CODE REVIEW

File: test/generic/PuiseuxSeries-test.jl [hunk 1]
```diff
@@ -219,6 +219,17 @@ end
       @test f*(g + h) == f*g + f*h
       @test f*(g - h) == f*g - f*h
    end
+
+   # Regression test for Nemo issue 319
+   R,x = PuiseuxSeriesRing(ZZ, 4, "x");
+   cs = [one(ZZ), zero(ZZ), one(ZZ), zero(ZZ)];
+   f = R(R.laurent_ring(cs, 4, 4, 0, 1, false), 2);
```
Comment (rfourquet) [inline test/generic/PuiseuxSeries-test.jl]: No need for semicolons at the end of line (I know this comes from the issue!)
