### PR TITLE
Matrix documentation fix

### LINKED ISSUE #731: Fix minor misses in matrix-documentation
I noticed some minor misses in the online-documentation, for example the documentation code for `zero_matrix` exists, but doesn't appear in the online documentation (except under https://nemocas.github.io/AbstractAlgebra.jl/latest/matrix_spaces/#Constructors, but this doesn't seem to be searchable). I noticed some other errors, for which I will provide a fix for.

### PR DESCRIPTION
**Pull request by albinahlback**
Fixed minor things in the documentation.

### CODE REVIEW

File: src/generic/Matrix.jl [hunk 1]
```diff
@@ -249,7 +254,7 @@ and zeroes elsewhere. The matrix space must contain square matrices.
 one(a::AbstractAlgebra.MatSpace) = check_square(a)(1)
 
 @doc Markdown.doc"""
-    one(a::AbstractAlgebra.MatSpace)
+    one(a::MatElem)
```
Comment (wbhart) [inline src/generic/Matrix.jl:257]: This would change the documentation to be different to the actual function. That seems invalid.

File: docs/src/matrix.md [hunk 2]
```diff
@@ -215,6 +215,10 @@ length(::MatElem)
 isempty(::MatElem)
 ```
 
+```@docs
+zero_matrix(::Ring, ::Int, ::Int)
```
Comment (wbhart) [inline docs/src/matrix.md:219]: This function is part of the matrix interface and must be implemented by all matrix types. It isn't functionality provided generically for all matrix types by AbstractAlgebra. Therefore documenting it here is incorrect.

File: src/generic/Matrix.jl [hunk 3]
```diff
@@ -232,6 +232,11 @@ zero(x::MatrixElem, R::Ring, r::Int, c::Int) = zero!(similar(x, R, r, c))
 zero(x::MatrixElem, R::Ring=base_ring(x)) = zero(x, R, nrows(x), ncols(x))
 zero(x::MatrixElem, r::Int, c::Int) = zero(x, base_ring(x), r, c)
 
+@doc Markdown.doc"""
```
Comment (wbhart) [inline src/generic/Matrix.jl:235]: I don't personally object to this, but technically zero is documented elsewhere in the system and there is currently a push to deduplicate the documentation, rather than to introduce many new docstrings for the same thing.

File: src/generic/Matrix.jl [hunk 4]
```diff
@@ -6019,7 +6024,7 @@ end
 ################################################################################
 
 @doc Markdown.doc"""
-    zero_matrix(R::Ring, r::Int, c::Int) -> MatElem
+    zero_matrix(R::Ring, r::Int, c::Int)
```
Comment (wbhart) [inline src/generic/Matrix.jl:6027]: I personally do not like adding return types, so I'm ok with this change. However others in our group disagree and want them to be included sometimes and don't want them to be removed once added.

Not my decision, but one we have to live with.

File: src/generic/Matrix.jl [hunk 5]
```diff
@@ -232,6 +232,11 @@ zero(x::MatrixElem, R::Ring, r::Int, c::Int) = zero!(similar(x, R, r, c))
 zero(x::MatrixElem, R::Ring=base_ring(x)) = zero(x, R, nrows(x), ncols(x))
 zero(x::MatrixElem, r::Int, c::Int) = zero(x, base_ring(x), r, c)
 
+@doc Markdown.doc"""
+    zero(a::Generic.MatrixElem)
+
+Construct the zero matrix in the same matrix space as `a`.
+"""
 function zero!(x::MatrixElem)
```
Comment (rfourquet) [inline src/generic/Matrix.jl:240]: This docstring seems to be added to the wrong method?

File: src/generic/Matrix.jl (hunk 1 above)
Comment (albinahlback) [reply src/generic/Matrix.jl:257]: Hmm, we have one method `one(a::AbstractAlgebra.MatSpace)` as well as the method `one(a::MatElem)`. Then both documentations shouldn't point to `one(a::AbstractAlgebra.MatSpace)`? I'm sorry if there's something I am not understanding.

File: src/generic/Matrix.jl (hunk 4 above)
Comment (albinahlback) [reply src/generic/Matrix.jl:6027]: Thanks for your review, I will change this back!

File: src/generic/Matrix.jl (hunk 5 above)
Comment (albinahlback) [reply src/generic/Matrix.jl:240]: Yes, you're totally right.

File: docs/src/matrix.md (hunk 2 above)
Comment (albinahlback) [reply docs/src/matrix.md:219]: Okay, I will remove it then.

File: src/generic/Matrix.jl (hunk 3 above)
Comment (albinahlback) [reply src/generic/Matrix.jl:235]: Are you referring to [this](https://nemocas.github.io/AbstractAlgebra.jl/latest/module/#Base.zero-Union{Tuple{AbstractAlgebra.FPModule{T}},%20Tuple{T}}%20where%20T%3C:Union{RingElem,%20AbstractFloat,%20Integer,%20Rational})?

In relation to Nemo (it links to https://nemocas.github.io/AbstractAlgebra.jl/latest/matrix/), could it be valuable to have the `zero` function under `matrix.md` as well?

Comment (wbhart) [reply src/generic/Matrix.jl:235]: I wasn't referring to that. The zero function is not documented there. It is documented as an optional part of the Matrix interface. It's optional for a reason.

If you look on the matrix.md page, you will see it is already documented:

"As well as implementing the entire Matrix interface, including the optional functionality, there are many additional generic algorithms implemented for matrix spaces. We describe this functionality below."

It is current wisdom that we should not duplicate documentation, so although I wouldn't object to putting this in, I suspect it will simply be removed by people currently on a deduplication push. Perhaps wait until the pendulum swings the other way.

File: src/generic/Matrix.jl (hunk 1 above)
Comment (wbhart) [reply src/generic/Matrix.jl:257]: I am not sure what happened here. When I checked earlier, it seemed that the proposed change to the docstring did not match the function it was documenting. Now it seems to match. I'm a bit confused by that. Obviously your proposed change is correct.

File: src/generic/Matrix.jl [hunk 6]
```diff
@@ -6042,18 +6047,20 @@ end
...
-    identity_matrix(R::Ring, n::Int) -> MatElem
+    identity_matrix(R::Ring, n::Int)
 
 Return the $n \times n$ identity matrix over $R$.
 """
 identity_matrix(R::Ring, n::Int) = diagonal_matrix(one(R), n)
 
 @doc Markdown.doc"""
-    identity_matrix(M::MatElem{T}) where T <: RingElement
+    identity_matrix(M::MatElem{T}, [n::Int]) where T <: RingElement
```
Comment (wbhart) [inline src/generic/Matrix.jl:6057]: Look, I don't know if this is just some kind of GitHub glitch, but what I clearly see here is a change to a docstring that does not match the function it is documenting. There is no [n::Int] argument in the function, so I don't see why the docstring should be changed to that.

But perhaps GitHub is playing some kind of silly game here. I feel like attaching a screenshot so you can see what I mean.

**Comment by wbhart** [comment]
By the way, I do appreciate you trying to help out with the docs here, especially as you are a computational modular forms guy! Sorry it's so confusing at present. Obviously we have to do MUCH better, and it is a pet project of mine to improve our documentation substantially over the next few years, so I certainly appreciate the volunteer effort!

File: src/generic/Matrix.jl (hunk 6 above)
Comment (rfourquet) [reply src/generic/Matrix.jl:6057]: It's not a GitHub glitch. Although this kind of situtation is not ideal, it's sometimes prefered by some authors to attach a docstring which describes two distinct methods to only one of the methods in order to limit repetetion. One current example of this is the docstring for `similar` in Julia `Base` which is attached only to the method `similar(a::AbstractArray{T}) where {T}`, although the docstring describes more methods, with optional `element_type` and optional `dims`.

A slightly cleaner way is to attach the same docstring to both methods (there is a syntax for that, basically add after the docstring a list a `,`-separated signatures). Here having two distinct docstrings would also be fine I think, as the duplication would be low.

Comment (wbhart) [reply src/generic/Matrix.jl:6057]: We literally spent 3 months of HiWi time making sure all docstrings match the functions they are documenting. I'm not at all happy about reversing course on that. I think we should find another way.

**Comment by fieker** [comment]
On Mon, Jan 18, 2021 at 04:09:16AM -0800, Rafael Fourquet wrote:
> @rfourquet commented on this pull request.
> 
> 
> 
> >  
>  Return the $n \times n$ identity matrix over $R$.
>  """
>  identity_matrix(R::Ring, n::Int) = diagonal_matrix(one(R), n)
>  
>  @doc Markdown.doc"""
> -    identity_matrix(M::MatElem{T}) where T <: RingElement
> +    identity_matrix(M::MatElem{T}, [n::Int]) where T <: RingElement
> 
> It's not a GitHub glitch. Although this kind of situtation is not ideal, it's sometimes prefered by some authors to attach a docstring which describes two distinct methods to only one of the methods in order to limit repetetion. One current example of this is the docstring for `similar` in Julia `Base` which is attached only to the method `similar(a::AbstractArray{T}) where {T}`, although the docstring describes more methods, with optional `element_type` and optional `dims`.
> 
> A slightly cleaner way is to attach the same docstring to both methods (there is a syntax for that, basically add after the docstring a list a `,`-separated signatures). Here having two distinct docstrings would also be fine I think, as the duplication would be low. 
> 
Why is this cleaner?

**Comment by rfourquet** [comment]
> Why is this cleaner?

Consider:
```julia
"a" f() = 1
"b" f(x) = 1
"c" f(x, y) = 1
```
When you ask for the docstring for `f()`, `f(1)` or `f(1, 1)`, it returns the proper respective docstring. On the other hand, in 
```julia
"a and b" g() = 1
 g(x) = 1
"c" g(x, y) = 1
```
When you ask for the docstring of `g(1)`, it shows the concatenations of the docstrings of both `g()` and `g(x, y)`. It's not the end of the world of course.
The "cleaner" alternative I was mentioning is:
```julia
h() = 1
h(x) = 1
"a and b" h(), h(x)
"c" h(x, y) = 1
```
It behaves as expected, i.e. help for both `h()` or `h(1)` show only `"a and b"`, and not the help for `h(x, y)`.

**Comment by fieker** [comment]
On Mon, Jan 18, 2021 at 06:00:24AM -0800, Rafael Fourquet wrote:
> > Why is this cleaner?
> 
> Consider:
> ```julia
> "a" f() = 1
> "b" f(x) = 1
> "c" f(x, y) = 1
> ```
> When you ask for the docstring for `f()`, `f(1)` or `f(1, 1)`, it returns the proper respective docstring. On the other hand, in 
> ```julia
> "a and b" g() = 1
>  g(x) = 1
> "c" g(x, y) = 1
> ```
> When you ask for the docstring of `g(1)`, it shows the concatenations of the docstrings of both `g()` and `g(x, y)`. It's not the end of the world of course.
> The "cleaner" alternative I was mentioning is:
> ```julia
> h() = 1
> h(x) = 1
> "a and b" h(), h(x)
> "c" h(x, y) = 1
> ```
> It behaves as expected, i.e. help for both `h()` or `h(1)` show only `"a and b"`, and not the help for `h(x, y)`.
> 
So the point is that g(1) has no specific dicstring, hence you see all.
Thus the "solution" is to have docstrings for every signature.
However this seems to work only if the definitions are in the same
location/ file, and then, this is neat. Is this guaranteed by
Documenter?

**Comment by rfourquet** [comment]
> Is this guaranteed by Documenter?

It's documented in the Julia manual: https://docs.julialang.org/en/v1/manual/documentation/#Multiple-Objects

File: src/generic/Matrix.jl (hunk 6 above)
Comment (rfourquet) [reply src/generic/Matrix.jl:6057]: An alternative here is also to attach the docstring to the function, instead of the methods, e.g. 
```julia
"""
    identitty_matrix(M, [n::Int]) 

desciption
""" 
function identity_matrix end
```

**Comment by wbhart** [comment]
Even if a PR was totally rejected, it still raises useful issues. For example, you here raised the issue that stuff in our interface documentation was not searchable. This is indeed an important issue I was not aware of and we will need to figure out a way to solve this.

There's also the issue that we were already aware of that online documentation benefits from duplication, REPL documentation does not. This has implications, though we don't know how to solve this problem without orders of magnitude more volunteer effort at present.

File: src/generic/Matrix.jl (hunk 6 above)
Comment (albinahlback) [reply src/generic/Matrix.jl:6057]: Here I basically copied the appearance from the `diagonal_matrix` docs a couple of lines down. Could that approach wrong as well?

Comment (wbhart) [reply src/generic/Matrix.jl:6057]: I think so, yes. The reason is that quite clearly someone will come along in a month, long after it's forgotten why it's like that, and remove this, thinking that it's just a mistake. In my opinion it should be perfectly obvious that this is not the right way to solve this problem.

Of course I completely understand that you modeled it on what had already been done. I'm objecting to every instance of it, not just yours. Of course someone else may overrule me. I'm not the one making the decisions.

File: src/generic/Matrix.jl (hunk 3 above)
Comment (fingolfin) [reply src/generic/Matrix.jl]: As one of the people @wbhart refers to regarding the "deduplication push": what "we" object to is having the help function showing dozens or hundreds of near identical doc strings for things like `+`. I'd rather have only one in a central place (or three, or five, if there are different signatures to document; but the point: document each variant only once).

As such, I think I'd probably prefer if all functions of a given implicit "interface" were documented in one place -- so I'd not have suggested to remove the `zero_matrix` docstring above, even if there is no generic implementation...

**Comment by albinahlback** [comment]
Is there something to improve or something else to bring into this PR? I am simply adding `zero` to the online documentation since `one` is already there, as well as fixing a docstring.

**Review by thofma — APPROVED** [review]

**Review by wbhart — APPROVED** [review]
