### PR TITLE
fix: adjust to IJulia changes

### LINKED ISSUE #2208: 'Dummy error for jupyter' in IJulia 1.32
see https://github.com/JuliaLang/IJulia.jl/issues/1219

I think @aaruni96 is already looking in to this.

### PR DESCRIPTION
**Pull request by thofma**
Closes #2208, closes https://github.com/JuliaLang/IJulia.jl/issues/1219.

### CODE REVIEW

File: src/PrettyPrinting.jl [hunk 1]
```diff
@@ -262,18 +262,26 @@ macro enable_all_show_via_expressify(T)
        AbstractAlgebra.show_via_expressify(io, mi, x)
     end
 
-    function Base.show(io::IO, mi::MIME"text/latex", x::$(esc(T)))
+    function Base.showable(mi::MIME"text/latex", x::$(esc(T)))
        if isdefined(Main, :IJulia) && Main.IJulia.inited
```
Comment (JamesWrigley) [inline src/PrettyPrinting.jl:266]: Just so you know, this will cause invalidations because of binding partitions on 1.12: https://github.com/jheinen/GR.jl/pull/573

You might wanna check how many it causes with SnoopCompile, if it's only a few then it might not be worth making a package extension.

Comment (lgoettgens) [reply src/PrettyPrinting.jl:266]: Thanks for the pointer. I think we'll continue with this PR to immediately deliver a functional fix for our downstream packages, and then investigate the invalidations and possible other solutions in a future PR
