### PR TITLE
fix: make MPolyFactor module more robust

### LINKED ISSUE #1960: Bug (?) in `MPolyFactor` when coefficients are are not in a field
```
julia> R,(x,y) = ZZ[:x,:y]
(Multivariate polynomial ring in 2 variables over integers, AbstractAlgebra.Generic.MPoly{BigInt}[x, y])

julia> f = AbstractAlgebra.MPolyFactor.mfactor_char_zero((2*x+x)^2)
9 * x^2
```

Looking at the code, I think what effectively happens is that `f.unit` is set to the content of the polynomial. But really that should also be factorized.

So in this case I'd expect an error to be thrown because we don't implement `factor` for `BigInt`.

One can now quibble whether this is a bug, after all `AbstractAlgebra.MPolyFactor.mfactor_char_zero` is not `factor` and could just declare that it doesn't handle factorization in the coefficient ring. In that interpretation, it simply alllows itself to abuse the `unit` field of type `Fac` to store a non-unit.

### LINKED ISSUE #1961: Regarding the `MPolyFactor` code: using it, testing it, further development
I am unsure how to use the code in `src/algorithms/MPolyFactor.jl`. A comment there says:

> `#` experimental module whose parts can be overridden for specific types
> `#` main functions are mfactor_squarefree_char_zero and mfactor_char_zero

and I think it is used by @thofma in Hecke. (Hecke also contains a file `src/Misc/MPolyFactor.jl` which seems to be a different (perhaps older?) version of the same code, but it also doesn't seem to be used or even `include`d in Hecke?).

Unfortunately there are no real tests for it. In `test/algorithms/MPolyFactor-test.jl` a few helpers are tested and there is a comment saying:
> `#` not much to test because we would need working univariate factorization

But in practice it still seems to work in many cases, at least in char 0 and if the coefficients support factorization (for AA that means: coefficients are in a field):

```
julia> R,(x,y)=QQ[:x,:y]
(Multivariate polynomial ring in 2 variables over rationals, AbstractAlgebra.Generic.MPoly{Rational{BigInt}}[x, y])

julia> AbstractAlgebra.MPolyFactor.mfactor_char_zero((x+1)^2*(x-y+2))
1 * (x + 1)^2 * (x - y + 2)

julia> collect(ans)
2-element Vector{Pair{AbstractAlgebra.Generic.MPoly{Rational{BigInt}}, Int64}}:
     x + 1 => 2
 x - y + 2 => 1
```
Now it *does* sometimes run into an error due to missing `factor, e.g.::
```
julia> AbstractAlgebra.MPolyFactor.mfactor_char_zero((x+1)^2*(x-y+2)*(y^2-x))
ERROR: function factor is not implemented for argument
AbstractAlgebra.Generic.Poly{Rational{BigInt}}: x^2 + 2*x
```

But ironically in this example it can actually factor the polynomial itself:
```
julia> AbstractAlgebra.MPolyFactor.mfactor_char_zero(x^2 + 2*x)
1 * (x + 2) * x
```

But alas one can construct examples where it really fails:
```
julia> AbstractAlgebra.MPolyFactor.mfactor_char_zero(x^2 + 2*x + 2)
ERROR: function factor is not implemented for argument
AbstractAlgebra.Generic.Poly{Rational{BigInt}}: x^2 + 2*x + 2
```

This raises two questions in my mind:

1. would it make be useful for us to add a generic `factor(::MPolyRingElem`) method delegating to `AbstractAlgebra.MPolyFactor.mfactor_char_zero` at least if if the characteristic is 0 (and keeping issue #1960 in mind)
  - we have plenty of precedent for such functions, i.e., functions that only work if certain other functions are implemented, possibly functions for the coefficient ring
2. what about non-zero characteristic? What would be needed for that? Is anyone interested in this functionality? And is someone interested in implementing that?

### PR DESCRIPTION
**Pull request by thofma**
- keep the MPolyFactor module accepting arbitrary rings, but
  make the implementation more robust to capture illegal operations
  with non-invertible elements

Closes #1960 and closes #1961

(part of the work towards #1961 was #1973)

### CODE REVIEW

File: src/algorithms/MPolyFactor.jl [hunk 1]
```diff
@@ -1314,7 +1319,12 @@ function mfactor_squarefree_char_zero(a::E) where E
   # start with a monic version of a
   lc = coeff(a, 1)
   res.unit = R(lc)
-  res.fac = Dict{E, Int}(1//lc * a => 1)
+  if !is_unit(lc)
+    error("leading coefficient must be invertible")
+  end
+  # thus lc is invertible in K, which means that it is squarefree
+  # don't use `inv`, it is wrong for `BigInt`
+  res.fac = Dict{E, Int}(AbstractAlgebra.inv(lc) * a => 1)
```
Comment (fingolfin) [inline src/algorithms/MPolyFactor.jl:1327]: I don't understand, the line right above says bot to use `inv`?

maybe
```suggestion
  res.fac = Dict{E, Int}(a / lc => 1)
```

Comment (thofma) [reply src/algorithms/MPolyFactor.jl:1327]: `inv !== AbstractAlgebra.inv`. And `/` is illegal, since it is the wrong thing for `BigInt`.

Comment (thofma) [reply src/algorithms/MPolyFactor.jl:1327]: @fingolfin hopefully that answers your questions

File: src/algorithms/MPolyFactor.jl [hunk 2]
```diff
@@ -1314,7 +1319,12 @@ function mfactor_squarefree_char_zero(a::E) where E
   # start with a monic version of a
   lc = coeff(a, 1)
   res.unit = R(lc)
-  res.fac = Dict{E, Int}(1//lc * a => 1)
+  if !is_unit(lc)
+    error("leading coefficient must be invertible")
+  end
+  # thus lc is invertible in K, which means that it is squarefree
+  # don't use `inv`, it is wrong for `BigInt`
```
Comment (fingolfin) [inline src/algorithms/MPolyFactor.jl:1326]:
```suggestion
  # don't use `Base.inv`, it is wrong for `BigInt`
```

**Review by fingolfin — APPROVED** [review]
