### PR TITLE
Is_unit and is_nilpotent (with tests)

### LINKED ISSUE #11: isunit for univariate and multivariate polynomials is incorrect over Z/nZ
It's not true that a polynomial is a unit in its polynomial ring iff its constant coefficient is a unit. This has been assumed in the current implementation. For example, it isn't true over Z/nZ.

As it is actually quite expensive in general to compute this, we should look carefully where isunit has been used in generic code and remove references to it where this is not precisely what is required.

### PR DESCRIPTION
**Pull request by JohnAAbbott**
Fixes #11

### CODE REVIEW

File: src/LaurentMPoly.jl [hunk 1]
```diff
@@ -168,3 +168,31 @@ For information about the many ways to specify `varnames...` refer to [`polynomi
...
+
+###############################################################################
+#
+#   Some operations
+#
+###############################################################################
+
+function is_unit(f::T) where {T<:LaurentMPolyRingElem}
+  # **NOTE** f.mpoly is not normalized in any way
+  characteristic(parent(f)) == 1 && return true  # coeffs in zero ring
```
Comment (fingolfin) [inline src/LaurentMPoly.jl:181]:
```suggestion
  is_trivial(parent(f)) && return true  # coeffs in zero ring
```
... and similarly elsewhere

File: src/MPoly.jl [hunk 2]
```diff
@@ -425,16 +425,27 @@ end
...
+#    if is_constant(a)
+#       return is_unit(leading_coefficient(a))
+#    elseif is_domain_type(elem_type(coefficient_ring(a)))
+#       return false
+#    elseif length(a) == 1
+#       return false
+#    else
+#       throw(NotImplementedError(:is_unit, a))
+#    end
+# end
```
Comment (fingolfin) [inline src/MPoly.jl:438]:
```suggestion
```

File: src/MPoly.jl [hunk 3]
```diff
@@ -425,16 +425,27 @@ end
...
+function is_unit(f::T) where {T<:MPolyRingElem}
+  is_unit(constant_coefficient(f)) || return false
+  characteristic(parent(f)) == 1 && return true  # coeffs in zero ring
+  is_domain_type(elem_type(coefficient_ring(f))) && return (length(f)==1)
```
Comment (fingolfin) [inline src/MPoly.jl:442]: Isn't this equivalent to this (which is almost the old code just with one redundant case dropped and formatted with `&&` instead of `if/else`):
```suggestion
  is_constant(f) && return is_unit(constant_coefficient(f))
  is_domain_type(elem_type(coefficient_ring(f))) && return false
```
In particular if the polynomial ring is trivial then `is_constant(f)` should return `true anyway. And `length(f)==1` is just yet another way to express "is constant (but not zero)". 

Of course we also could add some comments:
```suggestion
  # for constant polynomials we simply delegate to the base ring
  is_constant(f) && return is_unit(constant_coefficient(f))

  # over an integral domain, non-constant polynomials are never units
  is_domain_type(elem_type(coefficient_ring(f))) && return false
```

File: src/MPoly.jl [hunk 4]
```diff
@@ -445,6 +456,18 @@ function content(a::MPolyRingElem{T}) where T <: RingElement
    return z
 end
 
+
+function is_nilpotent(f::T) where {T<:MPolyRingElem}
+  is_domain_type(elem_type(coefficient_ring(f))) && return (is_zero(f))
```
Comment (fingolfin) [inline src/MPoly.jl:461]:
```suggestion
  is_domain_type(elem_type(coefficient_ring(f))) && return is_zero(f)
```

File: src/MPoly.jl [hunk 5]
```diff
@@ -445,6 +456,18 @@ function content(a::MPolyRingElem{T}) where T <: RingElement
...
+  for i in 1:length(f)
+    if !is_nilpotent(coeff(f, i))
+      return false
+    end
+  end
+  return true
```
Comment (fingolfin) [inline src/MPoly.jl:467]: Could also do this:
```
  return all(is_nilpotent, coefficients(f))
```
but I didn't time it or anything

File: src/Poly.jl [hunk 6]
```diff
@@ -222,18 +222,42 @@ function is_monic(a::PolynomialElem)
...
-   elseif !is_unit(coeff(a, 0)) || is_unit(coeff(a, length(a) - 1))
+    end
+  end
+  return true
+end
+
+
+function is_nilpotent(f::T) where {T<:PolyRingElem}
+  is_domain_type(elem_type(coefficient_ring(f))) && return (is_zero(f))
+  for i in 0:degree(f)
```
Comment (fingolfin) [inline src/Poly.jl:252]: I think the same code I suggested for `MPolyRingElem` might work here as well

File: src/Poly.jl [hunk 7]
```diff
@@ -222,18 +222,42 @@ function is_monic(a::PolynomialElem)
...
       return false
-   else
-      throw(NotImplementedError(:is_unit, a))
-   end
+    end
+  end
+  return true
 end
 
+
```
Comment (fingolfin) [inline src/Poly.jl:260]:
```suggestion
```

File: src/Rings.jl [hunk 8]
```diff
@@ -101,6 +101,13 @@ is_exact_type(R::Type{T}) where T <: RingElem = true
 # false unless explicitly specified
 is_domain_type(R::Type{T}) where T <: RingElem = false
 
+
+# Default implementation: covers all integral domains
+function is_nilpotent(a::T) where {T <: RingElem}
```
Comment (fingolfin) [inline src/Rings.jl:106]: This code is also valid for non-commutative rings, such as matrix rings, isn't it? if so let's generalize it:
```suggestion
function is_nilpotent(a::T) where {T <: NCRingElem}
```
Of course it then should rather go into `src/NCRings.jl`

**Comment by thofma** [comment]
I don't think we can rely on any order when iterating over the coefficients. The only guarantee that we have is that `coefficients` and `exponent[_vectors]` have the same order. E.g., this is the implementation of `constant_coefficient`:
```
function constant_coefficient(p::MPolyRingElem{T}) where T <: RingElement
   if !iszero(p)
      for (c, v) in zip(coefficients(p), exponent_vectors(p))
         if iszero(v)
            return c
         end
      end
   end
   return zero(base_ring(p))
end
```

File: src/MPoly.jl (hunk 2 above)
Comment (JohnAAbbott) [reply src/MPoly.jl:438]: Thanks -- i plan to delete commented out code when the tests pass... if ever!

File: src/MPoly.jl (hunk 3 above)
Comment (JohnAAbbott) [reply src/MPoly.jl]: Not quite equivalent: we must check that `is_unit(constant_coefficient(f))` before the `is_domain_type` check.  Luckily the test-suite detected the mistake... I didn't spot it (oops)

**Comment by JohnAAbbott** [comment]
I notice that there are tests of `is_unit` for Laurent series: for instance
```
./generic/LaurentSeries-test.jl:156:   @test is_unit(-1 + x + 2x^2)
```
Should I disable these tests?  I have not yet checked which code would be called...
Perhaps it is simpler to leave things be?

File: src/MPoly.jl (hunk 3 above)
Comment (JohnAAbbott) [reply src/MPoly.jl]: Seems to be OK now... just waiting for GitHub to confirm.  Running the tests locally went OK.

File: src/Rings.jl (hunk 8 above)
Comment (JohnAAbbott) [reply src/Rings.jl]: Done!

File: src/Poly.jl (hunk 7 above)
Comment (JohnAAbbott) [reply src/Poly.jl:228]: I'm no longer sure which blank line was referred to.  I hope the new draft is laid out more along the desired lines.

**Comment by JohnAAbbott** [comment]
Current blockage:  in `docs/src/polynomial.md`  around line 333 there is a call to `remove(5g^3, g)` which calls `is_unit` internally.  Then a recursive call triggers an error:
```
julia> remove(5g^3, g)
ERROR: function is_nilpotent is not implemented for argument
EuclideanRingResidueRingElem{AbstractAlgebra.Generic.Poly{Rational{BigInt}}}: 2*x

Stacktrace:
 [1] is_nilpotent(a::EuclideanRingResidueRingElem{AbstractAlgebra.Generic.Poly{Rational{BigInt}}})
   @ AbstractAlgebra ~/OSCAR/GIT/AbstractAlgebra.jl/src/NCRings.jl:161
 [2] is_unit(f::AbstractAlgebra.Generic.Poly{EuclideanRingResidueRingElem{AbstractAlgebra.Generic.Poly{Rational{BigInt}}}})
   @ AbstractAlgebra ~/OSCAR/GIT/AbstractAlgebra.jl/src/NCPoly.jl:805
 [3] remove(z::AbstractAlgebra.Generic.Poly{EuclideanRingResidueRingElem{…}}, p::AbstractAlgebra.Generic.Poly{EuclideanRingResidueRingElem{…}})
   @ AbstractAlgebra ~/OSCAR/GIT/AbstractAlgebra.jl/src/Poly.jl:1572
```
I wonder why it does not call `function is_unit(a::ResElem)` defined around line 83 in `src/Residue.jl`??

**Comment by JohnAAbbott** [comment]
Sorry:  I can't read!  The problem is the missing `is_nilpotent` function, not `is_unit`

**Comment by fingolfin** [comment]
> I notice that there are tests of `is_unit` for Laurent series: for instance
> 
> ```
> ./generic/LaurentSeries-test.jl:156:   @test is_unit(-1 + x + 2x^2)
> ```
> 
> Should I disable these tests? I have not yet checked which code would be called... Perhaps it is simpler to leave things be?

I don't understand. Why would you disable the tests?

Anyway, checking what code is called shouldn't be hard with `@edit` and `@less`, right?

File: src/MPoly.jl [hunk 9]
```diff
@@ -425,16 +425,19 @@ end
...
-      return false
-   else
-      throw(NotImplementedError(:is_unit, a))
-   end
+function is_unit(f::T) where { T<:MPolyRingElem }
+  # for constant polynomials we delegate to the coefficient ring:
+  is_constant(f) && return is_unit(constant_coefficient(f))
+  # Here deg(f) > 0; over an integral domain, non-constant polynomials are never units:
+  is_domain_type(elem_type(coefficient_ring(f))) && return false
+  for (c, expv) in zip(coefficients(f), exponent_vectors(f))
```
Comment (fingolfin) [inline src/MPoly.jl:433]: Can we add a comment explaining the math? E.g.
```suggestion
  # A polynomial over a commutative ring is a unit if and only if its
  # constant term is a unit and all other coefficients are nilpotent.
  # See URL/BOOKREF/SOMETHING for a proof.
  for (c, expv) in zip(coefficients(f), exponent_vectors(f))
```
Obviously with a suitable source inserted.

File: src/MPoly.jl [hunk 10]
```diff
@@ -425,16 +425,19 @@ end
...
+    if is_zero(expv)
+      is_unit(c) || return false
+    else
+      is_nilpotent(c) || return false;
```
Comment (fingolfin) [inline src/MPoly.jl:437]:
```suggestion
      is_nilpotent(c) || return false
```
Semicolons keep creeping in ;-).


Anyway, this looks really nice now, thanks :-)

File: src/MPoly.jl [hunk 11]
```diff
@@ -445,6 +448,13 @@ function content(a::MPolyRingElem{T}) where T <: RingElement
    return z
 end
 
+
+function is_nilpotent(f::T) where {T<:MPolyRingElem}
+  is_domain_type(elem_type(coefficient_ring(f))) && return is_zero(f)
```
Comment (fingolfin) [inline src/MPoly.jl:453]:
```suggestion
function is_nilpotent(f::MPolyRingElem{T}) where {T}
  is_domain_type(T) && return is_zero(f)
```
would be IMHO more idiomatic (and simply much shorter to read).

The same could of course be used in `is_unit` above and elsewhere.

File: src/MPoly.jl [hunk 12]
```diff
@@ -445,6 +448,13 @@ function content(a::MPolyRingElem{T}) where T <: RingElement
...
+  return all(is_nilpotent, coefficients(f))
+end
+
+
 function is_zero_divisor(x::MPolyRingElem{T}) where T <: RingElement
```
Comment (fingolfin) [inline src/MPoly.jl:458]: Unrelated to this PR, but I wonder: should we also optimize this for domain types
```suggestion
function is_zero_divisor(x::MPolyRingElem{T}) where T <: RingElement
  is_domain_type(T) && return is_zero(f)
```

File: src/Rings.jl [hunk 13]
```diff
@@ -101,6 +101,7 @@ is_exact_type(R::Type{T}) where T <: RingElem = true
 # false unless explicitly specified
 is_domain_type(R::Type{T}) where T <: RingElem = false
 
+
```
Comment (fingolfin) [inline src/Rings.jl:104]:
```suggestion
```

File: src/NCRings.jl [hunk 14]
```diff
@@ -155,6 +155,13 @@ julia> is_unit(ZZ(-1)), is_unit(ZZ(4))
 """
 function is_unit end
 
+# Default implementation: covers all integral domains
+function is_nilpotent(a::T) where { T <: NCRingElem }
+  is_domain_type(typeof(a)) && return is_zero(a)
```
Comment (fingolfin) [inline src/NCRings.jl:160]:
```suggestion
function is_nilpotent(a::T) where {T <: NCRingElem}
  is_domain_type(T) && return is_zero(a)
```
Julia convention is to write `{T <: NCRingElem}` not `{ T <: NCRingElem }`

File: src/MPoly.jl (hunk 11 above)
Comment (JohnAAbbott) [reply src/MPoly.jl:453]: OK, I'll try.  I have found `is_domain_type` to be quite obstreperous, which is why I have used work-arounds.  Maybe I should update...

File: src/NCRings.jl (hunk 14 above)
Comment (JohnAAbbott) [reply src/NCRings.jl:160]: I can do what you prefer, but there are **lots** of other functions which use different spacing in the `where` clause _e.g._ no curly brackets, no spaces around `<:`,...

File: src/MPoly.jl (hunk 12 above)
Comment (JohnAAbbott) [reply src/MPoly.jl:458]: Seems reasonable.  I'll try it -- just to make sure there are no unintended consequences.

Comment (JohnAAbbott) [reply src/MPoly.jl:458]: It works fine; not sure it brings any measurable benefit, but the code is there now.

File: src/MPoly.jl (hunk 11 above)
Comment (fingolfin) [reply src/MPoly.jl:453]: Could you clarify what you found problematic about `is_domain_type`? What are you "working around"?

File: src/julia/Rational.jl [hunk 15]
```diff
@@ -40,6 +40,8 @@ one(::Rationals{T}) where T <: Integer = Rational{T}(1)
 
 is_unit(a::Rational) = a != 0
 
+is_nilpotent(a::Rational) = (a == 0)
```
Comment (fingolfin) [inline src/julia/Rational.jl:43]: Redundant?

File: src/julia/Integer.jl [hunk 16]
```diff
@@ -42,6 +42,8 @@ one(::Integers{T}) where T <: Integer = T(1)
 
 is_unit(a::Integer) = a == 1 || a == -1
 
+is_nilpotent(a::Integer) = is_zero(a)
```
Comment (fingolfin) [inline src/julia/Integer.jl:45]: Redundant?

File: test/generic/MPoly-test.jl [hunk 17]
```diff
@@ -1727,3 +1714,115 @@ end
...
+## MPoly over ZeroRing
+@testset "Nilpotent/unit for ZeroRing[x,y]" begin
+  P,(x,y) = polynomial_ring(ZeroRing, ["x", "y"]);
+  @test is_nilpotent(P(0))
+  @test is_nilpotent(P(1))
+  @test is_nilpotent(x)
+  @test is_nilpotent(-x)
+  @test is_nilpotent(x+y)
+  @test is_nilpotent(x-y)
+  @test is_nilpotent(x*y)
```
Comment (fingolfin) [inline test/generic/MPoly-test.jl:1733]: Instead of adding these tests (which are very similar each time) into multiple places, it would be better to test them to the general ring interface test suite in `test/Rings-conformance-tests.jl` so that the tests get run for all our ring implementations (well, at least all that use the conformance tests).

Of course this may then reveal further issues, but so be it.

**Comment by fingolfin** [comment]
As I expressed on several occasions, it'd be perfectly fine to ignore series completely for now, focus on getting the rest right, then *after* that is ready and merged, think more about dealing with series. So that we get the "easier" (not easy) bits done and usable, instead of getting bogged down in the more complicated (and less useful for us, currently) bits.

But since you are asking: we do implement `is_zero` and `is_one` for these rings, no? Then my view point would be that there is a clear definition for `is_nilpotent` and `is_unit`, too, no? If there is a positive integer `k` such that `is_zero(x^k)` holds, then `x` is nilpotent.  And likewise, if there is a `y` such that `is_one(x*y)` then `x` is a unit.

Now whether this is *useful* is another question -- which is part of why I'd be OK with us raising an error if one of these functions is called on a series element.

**Comment by fingolfin** [comment]
BTW, note that doctests in `docs/src/polynomial.md` are failing

**Comment by fingolfin** [comment]
I'd like to add that despite my many minor nitpicks, overall this PR seems to be shaping up and headed in the right direction. Thank you.

File: src/MPoly.jl [hunk 18]
```diff
@@ -445,8 +451,17 @@ function content(a::MPolyRingElem{T}) where T <: RingElement
    return z
 end
 
+
+function is_nilpotent(f::T) where {T<:MPolyRingElem}
+#  is_domain_type(elem_type(coefficient_ring(f))) && return is_zero(f)
```
Comment (fingolfin) [inline src/MPoly.jl:456]: That's not right. You need
```suggestion
function is_nilpotent(f::MPolyRingElem{T}) where {T <: RingElement}
```
`is_domain_type` needs to be given the element type of the ring we want to consider -- and that is also precisely the type parameter used for `MPolyRingElem`, `PolyRingElem`, `MatElem` etc. etc.

Comment (fingolfin) [reply src/MPoly.jl:456]: Ah, but thinking more about this, of course we also implement `is_domain_type` "recursively" for `MPolyRingElem`, so this will work after all. Sorry for the noise

File: src/MPoly.jl (hunk 11 above)
Comment (JohnAAbbott) [reply src/MPoly.jl]: Seems to work now -- I no longer recall what problem I had.  Sorry!

File: src/julia/Integer.jl (hunk 16 above)
Comment (JohnAAbbott) [reply src/julia/Integer.jl:45]: Not redundant: the point is that rings in `AbstractAlgebra` having integer or rational coefficients use `BigInt` or `Rational{BigInt}` to represent the values (rather than Oscar types).  I suppose a similar argument applies to the `is_unit` functions which already have specializations for `Integer` and `Rational`.

File: src/julia/Rational.jl (hunk 15 above)
Comment (JohnAAbbott) [reply src/julia/Rational.jl:43]: Not redundant: see comment below.

**Comment by JohnAAbbott** [comment]
Right now I don't know how to write a test which will cover the lines which the codecov bot complained about.  I don't think it is important to cover them.

File: src/NCRings.jl [hunk 19]
```diff
@@ -155,6 +155,13 @@ julia> is_unit(ZZ(-1)), is_unit(ZZ(4))
 """
 function is_unit end
 
+# Default implementation: covers all integral domains
+function is_nilpotent(a::T) where {T <: NCRingElem}
```
Comment (thofma) [inline src/NCRings.jl:159]:
```suggestion
function is_nilpotent(a::T) where {T <: NCRingElement}
```

File: src/julia/Integer.jl (hunk 16 above)
Comment (thofma) [reply src/julia/Integer.jl:45]: They are redundant if the "generic" version allows `NCRingElement` instead of `NCRingElem` (which includes `Rational` and `Integer`). So yes, it should be removed and the other method adjusted.

File: src/NCRings.jl (hunk 19 above)
Comment (JohnAAbbott) [reply src/NCRings.jl:159]: Changing `NCRingElem` to `NCRingElement` would appear to allow floating-point arguments; do we wish to allow that?   It would make the specializations for `Integer` and `Rational` redundant (as Max queried earlier).  My preference would be to keep the _status quo_.  Presumably, if we do make this change, then the analogous change should also be made to `is_unit` - right?

Comment (JohnAAbbott) [reply src/NCRings.jl:159]: BTW `is_unit` does have a method for `AbstractFloat` -- is that intentional?

Comment (JohnAAbbott) [reply src/NCRings.jl]: Change made, and pushed.

File: src/julia/Integer.jl (hunk 16 above)
Comment (JohnAAbbott) [reply src/julia/Integer.jl]: Removed the specialization for `Integer` after changing the generic implementation to `NCRingElement`

File: src/NCRings.jl [hunk 20]
```diff
@@ -155,6 +155,25 @@ julia> is_unit(ZZ(-1)), is_unit(ZZ(4))
...
+@doc raw"""
+    is_nilpotent(a::T) where {T <: NCRingElement}
+
+Return true iff $a$ is nilpotent, i.e. a^k == 0 for some k.
+
+# Examples
+```jldoctest
+julia> ZZ720,_ = residue_ring(ZZ,720);
+julia> S, x = polynomial_ring(QQ, :x);
+julia> is_nilpotent(30*x), is_nilpotent(30+90*x), is_nilpotent(S(15))
```
Comment (fingolfin) [inline src/NCRings.jl:167]:
```suggestion
julia> S, x = polynomial_ring(QQ, :x);

julia> is_nilpotent(30*x), is_nilpotent(30+90*x), is_nilpotent(S(15))

```

File: src/MPoly.jl (hunk 18 above)
Comment (fingolfin) [inline src/MPoly.jl:456]:
```suggestion
```

File: src/MPoly.jl [hunk 21]
```diff
@@ -425,16 +425,22 @@ end
...
-      throw(NotImplementedError(:is_unit, a))
-   end
+function is_unit(f::T) where { T<:MPolyRingElem }
+  # for constant polynomials we delegate to the coefficient ring:
+  is_constant(f) && return is_unit(constant_coefficient(f))
+  # Here deg(f) > 0; over an integral domain, non-constant polynomials are never units:
+  is_domain_type(T) && return false
+  # A polynomial over a commutative ring is a unit iff its
+  # constant term is a unit and all other coefficients are nilpotent:
+  # see ????? for a proof.
```
[the remark this answers is not in the document]
Comment (fingolfin) [reply src/MPoly.jl:435]:
```suggestion
  # see e.g. <https://kconrad.math.uconn.edu/blurbs/ringtheory/polynomial-properties.pdf> for a proof.
```

File: src/MPoly.jl [hunk 22]
```diff
@@ -445,8 +451,16 @@ function content(a::MPolyRingElem{T}) where T <: RingElement
    return z
 end
 
+
+function is_nilpotent(f::T) where {T<:MPolyRingElem}
```
Comment (fingolfin) [inline src/MPoly.jl:455]:
```suggestion
function is_nilpotent(f::T) where {T <: MPolyRingElem}
```

File: src/algorithms/LaurentPoly.jl [hunk 23]
```diff
@@ -138,12 +138,28 @@ function is_monomial_recursive(p::LaurentPolyRingElem)
    is_monomial_recursive(coeff(p, dr[]))
 end
 
-function is_unit(p::LaurentPolyRingElem)
-   dr = degrees_range(p)
-   length(dr) == 1 || return false
-   is_unit(coeff(p, dr[]))
+function is_unit(f::T) where {T<:LaurentPolyRingElem}
```
Comment (fingolfin) [inline src/algorithms/LaurentPoly.jl:141]:
```suggestion
function is_unit(f::T) where {T <: LaurentPolyRingElem}
```

File: src/generic/LaurentMPoly.jl [hunk 24]
```diff
@@ -109,15 +109,28 @@ function Base.inv(a::LaurentMPolyWrap)
     return LaurentMPolyWrap(parent(a), inv(ap), neg!(ad, ad))
 end
 
-function is_unit(a::LaurentMPolyWrap)
-    (ap, ad) = _normalize(a)
-    if is_domain_type(elem_type(coefficient_ring(a))) || length(ap) <= 1
-        return is_unit(ap)
-    else
-        throw(NotImplementedError(:is_unit, a))
+function is_unit(f::T) where {T<:LaurentMPolyRingElem}
```
Comment (fingolfin) [inline src/generic/LaurentMPoly.jl:112]:
```suggestion
function is_unit(f::T) where {T <: LaurentMPolyRingElem}
```

File: src/generic/LaurentMPoly.jl [hunk 25]
```diff
@@ -109,15 +109,28 @@ function Base.inv(a::LaurentMPolyWrap)
...
+    if unit_seen || !is_unit(coeff(f.mpoly, i))
+      return false
+    end
+    unit_seen = true
+  end
+  return unit_seen
 end
 
+
+function is_nilpotent(f::T) where {T<:LaurentMPolyRingElem}
```
Comment (fingolfin) [inline src/generic/LaurentMPoly.jl:129]:
```suggestion
function is_nilpotent(f::T) where {T <: LaurentMPolyRingElem}
```

File: src/algorithms/LaurentPoly.jl [hunk 26]
```diff
@@ -138,12 +138,28 @@ function is_monomial_recursive(p::LaurentPolyRingElem)
...
+    if unit_seen || !is_unit(coeff(f.poly, i))
+      return false
+    end
+    unit_seen = true
+  end
+  return unit_seen
 end
 
+
+function is_nilpotent(f::T) where {T<:LaurentPolyRingElem}
```
Comment (fingolfin) [inline src/algorithms/LaurentPoly.jl:158]:
```suggestion
function is_nilpotent(f::T) where {T <: LaurentPolyRingElem}
```

**Review by fingolfin — APPROVED** [review]

File: test/generic/MPoly-test.jl (hunk 17 above)
Comment (fingolfin) [reply test/generic/MPoly-test.jl:1733]: Just to summarize our discussion: we should merge this as-is. Some of the tests can't be easily done in the general conformance tests.

However, we should add *some* tests to the general conformance tests. I'll open an issue for that.

File: src/NCRings.jl [hunk 27]
```diff
@@ -155,6 +155,27 @@ julia> is_unit(ZZ(-1)), is_unit(ZZ(4))
...
+Return true iff $a$ is nilpotent, i.e. a^k == 0 for some k.
+
+# Examples
+```jldoctest
+julia> ZZ720,_ = residue_ring(ZZ,720);
+julia> S, x = polynomial_ring(QQ, :x);
+
+julia> is_nilpotent(30*x), is_nilpotent(30+90*x), is_nilpotent(S(15))
+
+(true, true, false)
```
Comment (fingolfin) [inline src/NCRings.jl:170]:
```suggestion
julia> ZZ720,_ = residue_ring(ZZ,720);

julia> S, x = polynomial_ring(QQ, :x);

julia> is_nilpotent(30*x), is_nilpotent(30+90*x), is_nilpotent(S(15))
(true, true, false)
```

File: src/NCRings.jl [hunk 28]
```diff
@@ -155,6 +155,27 @@ julia> is_unit(ZZ(-1)), is_unit(ZZ(4))
...
+Return true iff $a$ is nilpotent, i.e. a^k == 0 for some k.
+
+# Examples
+```jldoctest
+julia> ZZ720,_ = residue_ring(ZZ,720);
+
+julia> S, x = polynomial_ring(QQ, :x);
+
+julia> is_nilpotent(30*x), is_nilpotent(30+90*x), is_nilpotent(S(15))
+(true, true, false)
```
Comment (fingolfin) [inline src/NCRings.jl:170]: @JohnAAbbott seems you and the code disagree as to what the correct output is?

Comment (fingolfin) [reply src/NCRings.jl:170]: Thepolynomial_ring should be over the ring created before, not over QQ. Fixed now
